### ISSUE TITLE
x64 Build: Error C2491: Definition of dllimport function not allowed 

### ISSUE THREAD

**Issue by rkalz** [Cxbx-Reloaded/Cxbx-Reloaded#1013]
I cloned the repo and tried to build it, got this error. 

It's complaining about functions in subhook.c and subhook_x86.c

**Comment by RadWolfie** [comment]
Had you tried any solution from stack overflow link? https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

I'm pretty sure you made a clone without a copy of submodules.

**Comment by rkalz** [comment]
I did `git clone --recurse-submodules https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/`

When I launch VS2017 however, I get 
![4d66aba15d](https://user-images.githubusercontent.com/18370951/38124412-116ab0b4-33a7-11e8-9acc-784d4b072315.png)

**Comment by RadWolfie** [comment]
x64 build is not supported for Cxbx-R. Also, xbox binaries are built with x86 architecture. Are you able to compile as x86 only? If so, this issue can be close.

**Comment by LukeUsher** [comment]
Cxbx-Reloaded requires to be run on 64-bit windows because WoW64 gives more address space to a 32bit process than is possible on native 32bit windows. It is curtently impossible to produce a 64-bit native version of Cxbx-Reloaded for a few reasons. 

1. We do not emulate the processor and Xbox code must run in a 32bit context. 
2. TLS / FS work differently on 32bit and 64bit processes
3. Inline assembly (required/used by some of our patches) is not possible on 64bit windows when using Visual Studio. 

2/3 of these issues could be solved by full emulation of the Xbox processor, and the third could be solved with a refactor of the codebase, or by building with GCC instead of MSVC. 

Both of these are more work than it is worth at the current moment in time.
