### ISSUE TITLE
Correctly implement D3DDevice_GetViewportOffsetAndScale

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#1129]
Currently, D3DDevice_GetViewportOffsetAndScale is implemented rather simple (it just sets all scale coordinates to 1.0 and all offset coordinates to 0.0).

To implement this correctly, we need to know a few test cases. Currently reported callers are:
* 007: From Russia with Love
* Army Men®: Sarge's War
* BeatDown - Fists of Vengeance
* Big Mutha Truckers
* Big Mutha Truckers 2
* Classified: The Sentinel Crisis
* Cold Fear
* Commandos SF
* Darkwatch
* Dr. Muto
* [GTA: Vice City](https://github.com/Cxbx-Reloaded/game-compatibility/issues/738)
* Jacked
* [Madagascar](https://github.com/Cxbx-Reloaded/game-compatibility/issues/111#issuecomment-386831434)
* [Max Payne 2](https://github.com/Cxbx-Reloaded/game-compatibility/issues/711#issuecomment-386829426)
* NBA LIVE 2005
* [NFS: Underground](https://github.com/Cxbx-Reloaded/game-compatibility/issues/82#issuecomment-386826795)
* [NFS: Underground 2](https://github.com/Cxbx-Reloaded/game-compatibility/issues/83#issuecomment-386827339)
* [PoP: The Sands of Time](https://github.com/Cxbx-Reloaded/game-compatibility/issues/396#issuecomment-386825771)
* Prince of Persia: T2T- see https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1109#issuecomment-386488587
* RPM Tuning
* Street Racing Syndicate
* Spongebob - Battle for Bikini Bottom
* The Incredibles: Rise of the Underminer
* The SpongeBob SquarePants Movie
* TMNT(R)2
* TMNT(R)3

TODO : Add more

Note : This has become more important now that we have a viewport scaling option

**Comment by Margen67** [comment]
Is this for games that show this error with or without the viewport scaling hack enabled?

**Comment by PatrickvL** [comment]
It'll be needed both with, and without the viewport-scaling hack enabled (that hack won't alter triggering the popup anyway).

**Comment by JohnGodgames** [comment]
**Jacked**
Please report that Jacked shows this test-case: D3DDevice_GetViewportOffsetAndScale
In EmuPatch_D3DDevice_GetViewportOffsetAndScale (d:\cxbx-reloaded\cxbx-reloaded\src\cxbxkrnl\emud3d8.cpp line 3375)

**Street Racing Syndicate**
Please report that Street Racing Syndicate shows this test-case: D3DDevice_GetViewportOffsetAndScale
In EmuPatch_D3DDevice_GetViewportOffsetAndScale (d:\cxbx-reloaded\cxbx-reloaded\src\cxbxkrnl\emud3d8.cpp line 3375)

**SpongeBob SquarePants Battle For Bikini Bottom**
Please report that SpongeBob SquarePants shows this test-case: D3DDevice_GetViewportOffsetAndScale
In EmuPatch_D3DDevice_GetViewportOffsetAndScale (d:\cxbx-reloaded\cxbx-reloaded\src\cxbxkrnl\emud3d8.cpp line 3375)

**Comment by blueshogun96** [comment]
I originally added this for Dr. Muto.  I never did find out what a proper implementation would look like.

Shogun

**Comment by ObiKKa** [comment]
This list in the OP is incredible. It's hard to search for the titles that have this issue in their issue pages because the notification messages usually only appear in screen snaps so you'd have to manually search for each issue in the game compat repo.

Found titles:
[GTA: Vice City](https://github.com/Cxbx-Reloaded/game-compatibility/issues/738)
[Madagascar](https://github.com/Cxbx-Reloaded/game-compatibility/issues/111#issuecomment-386831434)
[Max Payne 2](https://github.com/Cxbx-Reloaded/game-compatibility/issues/711#issuecomment-386829426)
[NFS: Underground](https://github.com/Cxbx-Reloaded/game-compatibility/issues/82)
[NFS: Underground 2](https://github.com/Cxbx-Reloaded/game-compatibility/issues/83#issuecomment-386827339)
[PoP: The Sands of Time](https://github.com/Cxbx-Reloaded/game-compatibility/issues/396#issuecomment-386825771)

I've searched through two pages' worth of the latest updated issues so I'm fairly these titles above are all that are left to add aside from future discoveries to be made by any tester.

**Comment by PatrickvL** [comment]
I think it's time to disable this popup - we've got more than enough test cases now

**Comment by ObiKKa** [comment]
It seems that this issue should have been a part of the [Popup meta-issue](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1157) from May 2018 onwards. But the latest PR link above has solved this test case last February of this year.
A new comment at Cold Dead's issue no longer produced this specific message.

**Comment by LukeUsher** [comment]
No longer relevant
