### ISSUE TITLE
Compile failure in Visual Studio 2015

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1170]
Cxbx-Reloaded doesn't compile in VS2015.
Need to add XTL:: to this - 
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/e1d87339769a5b3f2a8c2e5c13315289dcdd5053/src/CxbxKrnl/EmuD3D8/VertexShader.cpp#L1920
So it must be XTL::BOOL ....

**Comment by x1nixmzeng** [comment]
Thanks. We should really setup the automated build to check 2015 compatability!

**Comment by PatrickvL** [comment]
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1169/commits/8e66336cc39d6b7d02610121e30909b948427ec9

**Comment by Sarkie** [comment]
I think the plan is to leave VS2015 behind, and if it breaks, then the community can fix it if they want to.

**Comment by LukeUsher** [comment]
I agree with @Sarkie: Visual Studio 2015 has not been officially supported for quite some time. The only reason we list the runtime in the Readme is because some 3rd party libraries may still depend on the runtime. This has nothing to do with the actual compilation of the project.

If the community submit PRs to fix Visual Studio 2015, we'll accept them, sure, but we won't spend time and effort making sure all code remains compatible. There's no point sticking with older compiler versions (optimizations get better with newer compilers, and we get to use new functionality introduced in newer C++ standards)

**Comment by RadWolfie** [comment]
Little off topic for my post.

It's too bad Visual Studio 2017 are still getting a lot of updates to clients. Plus also very bad for VS 2015 and below aren't following C++ standard when should had been doing so, years ago. 😢 I will still wait until they finally stop sending bunch of updates for VS 2017 software.
