### ISSUE TITLE
SetRenderTarget performance improvement idea

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#1204]
@LukeUsher proposed this idea on discord : the performance impact of SetRenderTarget can be greatly reduced if we replace the calls to D3DXCreateSurfaceFromSurface with a completely different implementation: If we create a texture representing the Xbox back-buffer and render that to a fullscreen quad, it should be much faster as more work is done by the GPU. But that's also significantly more work on our side (development) and more places for things to go wrong.

**Comment by RadWolfie** [comment]
At first, I believe it came from this line from SetRenderTarget pull request.
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/aaf6579c45e10c933f7b1106732a60a3bd1fe74c/src/CxbxKrnl/EmuD3D8.cpp#L3194

Turns out, after commented this part out still doesn't resolve the performance issue.

Also, I'm saying performance dropped heavily is due to from SetRenderTarget pull request.

**Comment by LukeUsher** [comment]
Closing as the mentioned code (D3DXCreateSurfaceFromSurface) isn't even present anymore.
