### ISSUE TITLE
SetViewport returns 0x7FFFFFFF for width and height

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1261]
SetViewport returns 0x7FFFFFFF for width and height in many titles, even dashboard.
```
[0x17CC] D3D8: D3DDevice_SetViewport(
   pViewport            : 0x002FEBF4 -> X_D3DVIEWPORT8* {
   .X                    : 0
   .Y                    : 0
   .Width                : 7FFFFFFF
   .Height               : 7FFFFFFF
   .MinZ                 : 0
   .MaxZ                 : 1}
);
```
Upload titles here  with compatibility link to create relationship between issues, tracelogs also needed.
**Euro 2004**
https://github.com/Cxbx-Reloaded/game-compatibility/issues/781
[Euro2004_missinggfx_KrnlDebug.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/2083057/Euro2004_missinggfx_KrnlDebug.zip)

**Comment by PatrickvL** [comment]
Yesterday I've issueda pull request that fixes this

**Comment by RadWolfie** [comment]
@PatrickvL, the issue is after your pull request #1257. The kernel log attached here has commit c5e908ef to prove it.

Plus Luke state both xbox and Windows perform differently for 0x7FFFFFFF. Here's the comment from discord.
> LukeUsher: Basically, games call D3DDevice_SetViewPort with 7FFFFFFF to reset to default.
On Xbox, the SetViewPort function automatically clips to the render target size.
We don't implement that part yet

**Comment by gandalfthewhite19890404** [comment]
Please - create test-case fo this issue, it help to get more titles for tracking.
There well be MANY of it - even dashboard (4920) throws D3DDevice_SetViewport with such Width and Height.

**Comment by LukeUsher** [comment]
This turns out to not be a cause of missing graphics, just a call that fails with D3D8 but succeeds with D3D9: as long as we scale the given viewport size to the render target dimensions (like Xbox does), we'll be fine.

**Comment by PatrickvL** [comment]
For the missing graphics issues itself, better create an independent issue to track it by. Link to this one as one (dismissed) possible cause.

Another possible cause : we are presenting the first framebuffer that comes by SetRenderTarget, but Xbox title might target another framebuffer (because of multisampling or any other special effect)

**Comment by PatrickvL** [comment]
Let me clarify this :

PR #1257 doesn't change the arguments Xbox code passes into SetViewport, so you'll continue seeing 0x7FFFFFFF in the log.
What PR #1257 DOES do, is limit the values passed onto host SetViewport, so that call won't fail anymore (so we shouldn't see failed SetViewport log messages anymore).

With that, this issue can be closed.

PS: It's likely, that for this particular API, it wouldn't matter anymore if d3d8to9 was used or not.

**Comment by RadWolfie** [comment]
Ah, yes. It is passing down the arguments.

Hmm, it has one error. `[0x17CC] D3D8: D3DDevice_SetViewport : g_pD3DDevice->SetViewport D3D error (0x8876086C: D3DERR_INVALIDCALL: Invalid Call)`

Yet, the rest of the calls with 0x7FFFFFFF seems to be fine.
