### ISSUE TITLE
LLE flags text not being set correctly

### ISSUE THREAD

**Issue by Eurose209** [Cxbx-Reloaded/Cxbx-Reloaded#1274]
The LLE flags text is supposed to change when:

1. Emulation is not running
2. One or more of the actual LLE flags are changed.

Instead, the text does not change when emulation is not running, but the text does change when it is modified while emulation is running.

**Comment by RadWolfie** [comment]
I can confirm this issue on my end.

**Comment by RadWolfie** [comment]
Also, kernel process are suppose to send the info back to gui process to display accurate LLE flags going to be used.

**Comment by Voxel9** [comment]
I'm not sure if I'm 100% following this. I intentionally made it so that LLE flags text completely disappears when nothing is being emulated (when the Cxbx splash just shows), and re-appears once it's actually emulating something.
I could easily replicate the issue of LLE flags text changing whilst emulation was occuring, and that is a bug that we should definitely fix. But there shouldn't be any visible text changes at all whilst nothing is being emulated, because as I said earlier, it was made to be completely invisible during that time.

**Comment by RadWolfie** [comment]
@Voxel9, run a title. While it is running, change the LLE flag. Then you will see the update to GUI.

I'm checking to see if I am able to use existing define to send a custom message to gui process. Not everything can be emulated in HLE. Such as nxdk is not possible to emulate HLE, so gui's status need to rollback to lle flag set.

**Comment by Voxel9** [comment]
Yeah, that's what I kinda referred to, just the list of conditions OP wrote at the beginning threw me off a bit. But I completely get it now.
