### ISSUE TITLE
cannot map d-pad to xbox 360 controller/a title is currently emulating error

### ISSUE THREAD

**Issue by mamcocob64** [Cxbx-Reloaded/Cxbx-Reloaded#1306]

**Comment by ergo720** [comment]
What should we do about this? The d-pad issue is a known problem and the other should have been fixed by @RadWolfie in #1284, #1291 and #1279 (though those PRs are older than this issue unless the OP used an even older version of cxbxr)

**Comment by BenNottelling** [comment]
For the d-pad enable x-input

**Comment by RadWolfie** [comment]
`cannot map d-pad to xbox 360 controller` issue is duplicate of #28 (It is a very well known issue. We highly recommend to use XInput option whenever is available.)

As for title currently emulating error, it should at least fixed. If the issue persist, create a new issue instead of using this issue ticket ***with more details to reproduce the issue***. Since this issue ticket is a combine of two different issues. Plus doesn't have any details to reproduce the issue for "title currently emulating error".
