### ISSUE TITLE
When implementing JIT Compilation, do we translate all instructions or just ones that could cause exceptions

### ISSUE THREAD

**Issue by LukeUsher** [Cxbx-Reloaded/Cxbx-Reloaded#131]
Currently Cxbx-Reloaded operates by copying loading an Xbox executable in memory, and calling the entry point directly, running Xbox code as if it was a native application. 

As we move away from High Level Emulation to Low Level Emulation of the Xbox hardware, the Xbox code triggers an exception by accessing invalid memory. We need to handle this exception, check if it is a hardware access, handle that, and then resume execution.

The issue with this approach is that each individual hardware access has the overhead of calling an exception handler, this has already proven to be too slow to ever reach playable speeds.

The solution to this is to implement an X86-X86 JIT compiler, however, there are multiple methods of implementing this.

1. Still use the native code execution method, and when an exception is reached, use a JIT compiler to translate only the offending instruction, patching it to jmp to a memory handler. This is PatrickvL's preferred method.

2. Still use native code execution, when an exception is reached, use a JIT compiler to translate the remainder of the code block (It is likely that one function will access hardware multiple times, this would be the same as above, except with only one exception per function, however, the JIT would need to implement more instructions than method 1)

3. Use a JIT to translate all XBox code, preventing the need for the exception handler to ever be called, this is the most complicated option as it would require a complete JIT, which is an insane amount of work. There are concerns that this method would make Cxbx-Reloaded lose the direct code execution which makes it unique among current Xbox emulators. This is LukeUsher's (my) preferred method.

Methods 1 & 2 have similar benefits, except that Method 2 requires a slightly more complete JIT implementation than Method 1, and they keep our current direct code execution method.

Method 3 has many potential benefits, but it is unknown at this point if they will be worth the impact of losing direct code execution.

With Method 3:
We could emulate problematic CPU instructions properly, however we see fit. Currently we need to patch out some opcodes that cause issues.  (FS accesses being one of them)
We could pre-translate hardware accesses with a call to the memory handler, without relying on the initial exception handler. 
We could have a better control over timing, 
We could remove the need for patching FS register accesses, and instead have the JIT generate code that uses the in-memory KPCR instead of accessing FS, however because it would be handled during code translation, there would not be a possibility of false positives anymore. (I  have not seen any yet, but it's hard to believe it is impossible)
We could have a native 64-bit port, as the JIT could do X86-X64 code translation

However, Method 3 would require a complete JIT, this is a large amount of development work to undertake, additionally, each memory access would now have to go through a Memory handler function,  potentially slowing down memory accesses, also the initial translation of blocks of code on a function would be slow. Subsequent calls to the translated functions would be lightning fast as the translation would already have been done on the initial run. 

For Method 3 to be worth the extra development work, speed lost by translating blocks of code must be less than the speed lost by calling into an exception handler once per hardware accessing instruction

**Comment by PatrickvL** [comment]
Another question related to method 1 (just JIT instructions that cause access violations) is: Would it help to use a dictionary so we can re-use previously seen faulting intructions?

If this is implemented, the exception handler would initially just determine the instruction length of the offending opcode.
(There are implementations for this that don't require completely decoding of the instructions, so this can be a fast step.)
While the scanned length is not long enough to cater for a replacement patch (which will require 5 bytes), add more instructions.
(Note, that we have yet to determine how to handle branching instructions.)

Using the resulting array of bytes of a key, do a dictionary lookup for a previouly generated patch.
If not found, a patch must be generated and applied;

When generating patches, instructions that can be ignored  (like NOP's) don't have to be copied over into the patch.

For the offending instruction that must be emulated, it's either a privileged instruction, or a normal instruction.
Privileged instructions require their own handler. Cxbx already contains a few examples for this (see).
Normal instructions are probably easiest to replace it with the exact same opcode, but using a freed-up register instead of the (in)direct memory reference.
Memory-access(es) (which caused the access violation) must be handled via one or two callbacks (calling our read handler before the instruction and/or calling our write handler after the instruction).

When applying this patch, the previously determined number bytes must be replaced with a call to the patch, and if that doesn't cover the old bytes exactly, padded out with NOP's.

Once generated and applied, the patch can be added to a dictionary, BUT only when it's reusable.
Patches are reusable ONLY when the patched instructions didn't use any position-relative addressing.

Once the patch is in place, resume execution on the offending address, which is now patched.
Thus, the patch will (and MUST!) execute outside of the exception handler.

In some cases, an instruction that had to be taken along with the patched instruction could cause another exception;
We can either prevent that while generating the patch, by emulating memory-accesses for that (or those) instruction(s) too.
Or, just let the exception handler patch that instruction once it's executed from within the generated patch.
To ease this, we could pad out each instruction in the first-level patch with enough NOP's to cater for a potential second-level patch.

Any comments on this?

**Comment by Papermanzero** [comment]
Just an idea: Why don't you combine the approaches?
Means, you can start with the implementation of method 1/2, but in the end you will have method 3.

For method 2, you need to switch to JIT instructions, if you have exceptions. However due to the variety of games, there will be always a certain exception, which needs several JIT instructions. So, you have to increase the JIT instruction set step by step to increase the compatibility. But after a certain point, you will most likely have all instructions available as JIT. 
Then you have reached method 3.

**Comment by LukeUsher** [comment]
Closing, this issue hasn't been updated for nearly a year, and the discussions that took place back then hold less validity now. The future of Cxbx-R involves CPU emulation and/or virtualization, rather than 'backpatching'
