### ISSUE TITLE
FPS inconsistency (drops, variety) in Dashboard 4920 

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/Cxbx-Reloaded#1396]
NEED VERIFY ON DIFFERENT PC's CONFIGURATIONS.
I am noticed strange inconsistent behaviour of Dashboard 4920 emulation on my PC with several emulator's revisions. Settings - disabled all hacks except direct rendering to host, log is disabled (checked off File and Console).You may see fps drops, need to restart emulator again and again.

0b0c3429 (14 08 2018) - Optimization batch №1 - max FPS I've got - 50-53: If you restart emulation it may drop to 6-10, may require serveral times to restart for getting fps back to appropriate.
![image](https://user-images.githubusercontent.com/24764335/44248539-c63fe080-a1f3-11e8-9458-8071ac65524d.png)

96d0fcca (16 08 2018) - Implemented logging levels - FPS slightly dropped, may varies from 49-50 to 41-45, may require restarts, after restart fps may drop to 4-6, 6-10, 21-25, 40-45, etc:
![image](https://user-images.githubusercontent.com/24764335/44248580-1fa80f80-a1f4-11e8-9b56-8459313509d0.png)

6d15ab07 (17 08 2018) - Optimization batch №2: - FPS slightly dropped, may varies from 40-45, may require restarts, after restart fps often drops to 4-6, 6-10,
![image](https://user-images.githubusercontent.com/24764335/44248613-60a02400-a1f4-11e8-933d-a5f35ec94bea.png)

**Comment by LukeUsher** [comment]
Most of this is natural variation based on CPU load or whatever else.

However, large frame drops when using logging is normal: Especially debug level logging absolutely destroys performance, that's why it's not on by default, and why release builds never had debug logging enabled historically.

**Comment by gandalfthewhite19890404** [comment]
I'm using fatal error level with disabled modules (both of them).

**Comment by LukeUsher** [comment]
@gandalfthewhite19890404 it's still likely to affect performance because there are a lot more checks than there were before: 

With release builds, most logging was completely disabled (as in, not even compiled into the program at all), but to allow these to be configurable, they have had to have been replaced with a check to see if the log needs to happen or not.

It won't be a problem for long: Dashboard (like many other titles) has unstable performance due to the lack of a vertex cache, once that has been solved, the performance impact won't be as noticeable.

**Comment by PatrickvL** [comment]
@gandalfthewhite19890404 it'd be good to add an explaining closing comment.
