### ISSUE TITLE
How do I join the development team?

### ISSUE THREAD

**Issue by niko1point0** [Cxbx-Reloaded/Cxbx-Reloaded#1431]
I have been studying the Vulkan API for over a year, and I would like to help the Xbox emulation effort. Is there a way for me to join the team?

**Comment by FabxBs** [comment]
Everyone can contribute, as the readme says, you can do pull requests when you want and contribute, it's an open source project because of this.

**Comment by LukeUsher** [comment]
@niko1point0 Just fork the repo, and create a PR: We have no 'formal' development team, if you find something that needs improvement, feel free!

**Comment by niko1point0** [comment]
Ok, I will get to work. I am aware that DirectX 9 is the main API of the emulator, I am well equipped to use any API

**Comment by FabxBs** [comment]
@niko1point0  that's very good! we appreciate that you want to contribute, it will help the development :)

**Comment by RadWolfie** [comment]
Currently, multi-plugin support in HLE is being work on. See #1416 for last task on the list. Once implemented, you can start add support for Vulkan renderer from there.

Plus our filesystem and the coding are a mess.

P.S. Use our forums on [Gitter](https://gitter.im/Cxbx-Reloaded/Lobby) or [Discord](https://discord.gg/26Xjx23) for chat, support, and discussion. Issue tracker is being used for filing reports, general regressions, features, tasks, etc.

**Comment by PatrickvL** [comment]
@niko1point0 you're right on time! Just this week I've started on rendering plugins (see https://github.com/PatrickvL/Cxbx-Reloaded/commit/4a21de70a8bbe766d39c808213eb85bad417d85e for example).

Just follow Luke's suggestions, talk wth us on discord - we'll be glad to give you some guidance!

**Comment by LukeUsher** [comment]
@niko1point0 We'll chat on Discord later, but FYI: The reason many DirectX functions are marked as UNIMPLEMENTED or UNSUPPORTED are because we either don't understand how they work yet, or (more often) they are not supported by the host version of DirectX.

The Xbox runs a customized version of DirectX8, that is much more similar in functionality to OpenGL, it has many features and functions DirectX on PC doesn't have in any version.

We are slowly moving away from patching & implementing DirectX functions anyway, instead, we're interpreting the hardware 'pushbuffer' streams and rendering that way. This is both more stable and more accurate than function patching, and has better support for games in general.
