### ISSUE TITLE
Leftover "_XBOXKRNL_xxxx" Defines

### ISSUE THREAD

**Issue by RadWolfie** [Cxbx-Reloaded/Cxbx-Reloaded#1616]
Thanks to @NZJenkins' discovery. I have found there are bunch of `_XBOXKRNL_DEFEXTRN_` and  one of `_XBOXKRNL_LOCAL_`  legacy unused codes.

* [`_XBOXKRNL_DEFEXTRN_` (61 counts)](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/search?q=_XBOXKRNL_DEFEXTRN_)
* [`_XBOXKRNL_LOCAL_` (1 count)](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/search?q=_XBOXKRNL_LOCAL_)

Base on Visual Studio's find output, both defines aren't checked.

First reference of `_XBOXKRNL_DEFEXTRN_` is found in #820 issue.

**Comment by PatrickvL** [comment]
_XBOXKRNL_DEFEXTRN_ is indeed legacy, used back in the cxbx days to allow compilation of the kernel parts of cxbx, in order to produce an Xbox kernel library that could be imported as a regular library, so that the kernel thunk table would automatically be handled by the windows executable loader (or so I suspect it's intended use was) 
In any case, we won't be needing those anymore
