### ISSUE TITLE
Proposal: add new "error" log level to logging system

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#1630]
Currently, it's not possible to specify a log level which is more severe than a warning (WARNING level) but it's not a fatal error (FATAL level). Adding an ERROR level would solve this. Possible cases to use this level in the code are the following strings:
```
EmuLog(LOG_LEVEL::WARNING, "Failed to enumerate joysticks. The error was: %s", SDL_GetError());
EmuLog(LOG_LEVEL::WARNING, "Failed to open game controller %s. The error was %s\n", SDL_GameControllerNameForIndex(pDev->m_Index), SDL_GetError());
DBG_PRINTF("%s: VirtualAlloc failed to commit the memory! The error was %d\n", __func__, GetLastError());
DBG_PRINTF("%s: VirtualFree failed to decommit the memory! The error was %d\n", __func__, GetLastError());
DBG_PRINTF("VirtualProtect failed. The error code was %d\n", GetLastError());
DBG_PRINTF("Deallocation routine failed with error %d\n", GetLastError());
EmuLog(LOG_LEVEL::WARNING, "HCCA read error at physical address 0x%X", m_Registers.HcHCCA);
EmuLog(LOG_LEVEL::WARNING, "HCCA write error at physical address 0x%X", m_Registers.HcHCCA);
EmuLog(LOG_LEVEL::WARNING, "An unrecoverable error has occoured!\n");
EmuLog(LOG_LEVEL::WARNING, "ED read error at physical address 0x%X", current);
EmuLog(LOG_LEVEL::WARNING, "TD read error at physical address 0x%X", addr);
DBG_PRINTF("ISO_TD read error at physical address 0x%X\n", addr);
EmuLog(LOG_LEVEL::WARNING, "Error decoding opcode size at 0x%.8X", Eip);
EmuLog(LOG_LEVEL::WARNING, "Error decoding opcode at 0x%08X", e->ContextRecord->Eip);
EmuLog(LOG_LEVEL::WARNING, "0x%08X: Error while handling instruction %s (%u)", e->ContextRecord->Eip, Distorm_OpcodeString(info.opcode), info.opcode);
```
If this is accepted, than the logging gui should also be updated to allow the selection of this new log level.

**Comment by PatrickvL** [comment]
Perhaps it's also wise to accompany this with a re-design of the (test-case) popups, or at least determine whether level ERROR messages should pop up (too).

**Comment by RadWolfie** [comment]
Part of idea is in #1518 issue. Although, I think we should have a separate issue for the "central popup" function to reference the tickets to it.

**Comment by LukeUsher** [comment]
Logging errors is nice, but keep in mind that sometimes Errors are expected, so in many cases they should *not* have pop-up dialogs.

For example, every single game that uses the cache partition generates *many* NtCreateFile failed errors, because they first attempt to read from cache, then fallback to disc when cache doesn't exist.

**Comment by PatrickvL** [comment]
Unexpected behaviour is what we're interested in, indeed.
Error codes returned by Windows API calls are normal operation most of the time, so indeed should not be logged as errors. But merely as informative (perhaps debugging level) status codes

**Comment by RadWolfie** [comment]
I agree with @PatrickvL, we should lower the certain group of kernel APIs error's level down to either info or debug level. Might be best to use info level since there will be a massive output at debug level.

> Logging errors is nice, but keep in mind that sometimes Errors are expected, so in many cases they should not have pop-up dialogs.

Right, I currently do not have a full picture of the design at the moment. I had the design idea in my mind couple months which currently disappear. Basically, it will be smarter and able to handle for when to show and not to.
