### ISSUE TITLE
Sound emulation hangs for Virtua Cop 3 Chihiro 

### ISSUE THREAD

**Issue by Sky2310** [Cxbx-Reloaded/Cxbx-Reloaded#1634]
Hi, appreciate your team's work to keep this project active, but can you please look at sound emulation. I am trying to get Virtua Cop 3 Chihiro to work but sound lags at times in particular Act 2 after a couple of scenes after the bank station there is gun shooting sounds in the background that just hangs. Can you please try to fix? Many thanks

**Comment by ergo720** [comment]
Game specific issues should be reported in the [game-compatibility](https://github.com/Cxbx-Reloaded/game-compatibility) repository instead. For this game, there is an entry already [here](https://github.com/Cxbx-Reloaded/game-compatibility/issues/132). Closing.

**Comment by Sky2310** [comment]
Thank you Ergo720 for acknowledging this common sound problem it means a lot to many users.

**Comment by PatrickvL** [comment]
Seemingly incorrect emulation should also be documented accurately and concise in the game-specific issue, which could also be marked with the 'issue-sound' label.

**Comment by Sky2310** [comment]
> Seemingly incorrect emulation should also be documented accurately and concise in the game-specific issue, which could also be marked with the 'issue-sound' label.

Hi Patrick, I have provided as much details as I can. The graphics seems to be stable now but  on some stages like the second stage described above, the sound emulation stutters and is lags or echos in the background and doesn't go away. Would be great if you could please look into this as once fix, I would say Virtua Cop  3 is 100% compatible which is a big achievement for this emulator.

**Comment by PatrickvL** [comment]
@Sky2310 Thanks for the additional information. But as @ergo720 said, please add it to [the game-specific issue in our **game-compatibility** repository](https://github.com/Cxbx-Reloaded/game-compatibility/issues/132) instead of here.

Please also note that we have only one sound deveverloper (@RadWolfie) and we generally don't take requests on fixing specific titles.
Of course, when an issue is severe enough, it'll be addressed in due time, even when it only appears in one title (although, having more test-cases/titles with the same incorrect behavior is preferable, since that often helps finding the common denominator between them all).

**Comment by Sky2310** [comment]
> @Sky2310 Thanks for the additional information. But as @ergo720 said, please add it to [the game-specific issue in our **game-compatibility** repository](https://github.com/Cxbx-Reloaded/game-compatibility/issues/132) instead of here.
> 
> Please also note that we have only one sound deveverloper (@RadWolfie) and we generally don't take requests on fixing specific titles.
> Of course, when an issue is severe enough, it'll be addressed in due time, even when it only appears in one title (although, having more test-cases/titles with the same incorrect behavior is preferable, since that often helps finding the common denominator between them all).

Hi Patrick, any updates on the sound engine? I noticed some updates for sound on other games have been fixed in the latest release. Any chance this game can also be looked at? 

Many thanks

**Comment by PatrickvL** [comment]
We generally don't strive to get any specific game working. Instead we select individual issues, which suite our expertise and available time. Often, the ones that improve emulation accuracy are regarded as the most valuable issues to spend time on. If that benefits more than one game, we consider it a bonus, not a motivation. Most of my time I've spend on Cxbx-Reloaded was getting xdk samples to run, for example. Only now that we start running a few commercial games, we shift our testing efforts to them, but also mostly since they form good test-cases.
As for sound emulation, you'd still have to ask radwolfie. Also consider discussing this on our discord server instead of through issues...
