### ISSUE TITLE
Having trouble getting halo and marvel rise of the inhuman to run

### ISSUE THREAD

**Issue by j0nnay-aw83n** [Cxbx-Reloaded/Cxbx-Reloaded#1640]
hey so I have about 30 Xbox games and am having a hard time getting any of them to run. The games work when loaded onto my Xbox 360 but not on the emulator. I can some times get marvel rise of the inhumans to run but only 1/4 of the screen size up in the corner. And soon as I get past the menu it crashes, and games like fabel give me an error saying I’m missing a file, and  psychonots starts up but is stretched 2x my screen size and so I only get half the game on screen, I have a lot of games I’ve been testing and can’t seem to get any of them working. I have a ryzen 5 2200g and a rtx 2070. Maybe I’m messing up in the set up options or something. As well some of the games work with the experimental gpu Hack and some of them won’t work at all. Please let me know if this is a common thing or if it’s just me. Thabks

**Comment by RadWolfie** [comment]
Sound like each game has different issue which should be report in https://github.com/Cxbx-Reloaded/game-compatibility.

Plus filing a ticket here is not a place for get help support.

**Comment by literalmente-game** [comment]
@j0nnay-aw83n hi :wave: 
This is where we track issues related to the emulation directly, if you have something to report related to any specific game, you can do it here https://github.com/Cxbx-Reloaded/game-compatibility/issues

Use the search before making a new issue there, if the game is already reported you can add any new information you have to the already existing issue. 

You can close this issue here by clicking the "Close Issue" button

**Comment by j0nnay-aw83n** [comment]
Thank you I’ll do that next time
