### ISSUE TITLE
How to make games work?

### ISSUE THREAD

**Issue by Mechanical-sanity** [Cxbx-Reloaded/Cxbx-Reloaded#1740]
There's no option to open a game library and select games like the original ui. The new ui is so plain and has no options. How do you load games?

**Comment by RadWolfie** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/develop/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's issue tracker is not the place to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports or ask for support. You must use our forums on [Gitter](https://gitter.im/Cxbx-Reloaded/Lobby) or [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and will be close.

---
P.S. Check discord #cxbxr-help channel since I had provide a question and assistance couple minutes after your request for help.

**Comment by LukeUsher** [comment]
Also remember that Cxbx or Cxbx-Reloaded has *never* had a game-browser UI, it's not a feature we ever implemented, although we'd like to eventually.

The way to run games in Cxbx-R has always been File -> Open Xbe.
