### ISSUE TITLE
Review all disabled OOVPATables

### ISSUE THREAD

**Issue by jarupxx** [Cxbx-Reloaded/Cxbx-Reloaded#177]
Disabled OOVPATable has been registered in the OOVPATable.
Also patterns that are not being used has been left behind.
Maintaining them makes code easier to understand.

**Comment by PatrickvL** [comment]
To add a bit more detail to this :

In https://github.com/jarupxx/Cxbx-Reloaded/commit/1d50c6dfab2d669ebe625352d2b0e9364ddefffd#diff-409d7f5a6643712a79cab6f489120012 the `IDirectSoundBuffer_SetPitch` OOVPA was commented out,
and in https://github.com/jarupxx/Cxbx-Reloaded/commit/1d50c6dfab2d669ebe625352d2b0e9364ddefffd#diff-7b77ee97d3db4d00ea505ab41cfd02b9 the `IDirectSoundBuffer8_SetAllParameters` OOVPA was commented out.
There are many more OOVPA's that are currently commented out.

For this issue:
* create a list of commented-out OOVPA's
* review, discuss and decide per entry in this list what action should be taken for it
* apply these decisions to the code.


Possible actions per OOVPA:
* contradicts another OOVPA -> find out which one is correct, remove the faulty one
* duplicate to another OOVPA -> remove all duplicates (and mention this in the commit)
* overlaps with another OOVPA -> merge the two together if possible
* is an XREF but could be a PATCH registration (or vice versa) -> correct the declaration and registration
* could be an ALIAS -> find a test-case to verify this with, document this, uncomment and register OOVPA as an ALIAS
* completely wrong -> remove it (and mention why in the commit)
* OOVPA became obsolete -> remove it (and mention why in the commit, for example : patch no longer required because kernel has improved, or some other reason)
* potentially usefull -> keep around AND add all findings to the OOVPA in an extra comment
* certainly usefull -> enabled and register again

As always, describe all relevant details in the commit message, AND mention one or more test cases so correct behaviour can be independently verified.

Also, split up the changes in small, manageable commits

**Comment by PatrickvL** [comment]
@jarupxx Could you please read the above issue again, and add a summary comment with the points that are still relevant? I'll update the above list using that information.

**Comment by jarupxx** [comment]
Currently 170 OOVPA are comment out.
A lot of comment out OOVPA are registered in D3D 8.1.0.4034.
[disabled-OOVPATables.xlsx](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/909918/disabled-OOVPATables.xlsx)

**Comment by PatrickvL** [comment]
@jarupxx Is this work completed, now that HLE DB V2 is merged?

**Comment by jarupxx** [comment]
Now that HLE DB V2 is merged, this work completed.
