### ISSUE TITLE
Replace usage of SEH

### ISSUE THREAD

**Issue by darkf** [Cxbx-Reloaded/Cxbx-Reloaded#1860]
Several places in the emulation rely on SEH exception handling (`__try` / `__except`) for things like catching access violations for MMIO, but these aren't really supported on anything other than Windows+MSVC.

If they can't be replaced by more apropos Win32 API calls, perhaps use something like [AddVectoredExceptionHandler](https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-addvectoredexceptionhandler) for them instead.

**Comment by RadWolfie** [comment]
See #1341 pull request for [details](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1341#issuecomment-403999756).

`__try` / `__except` is only intended for display an error message to allow us attach Cxbx-Reloaded's emulated process locally and allow testers/users to file a report with kernel log dump if possible.

Even with `AddVectoredExceptionHandler` method, LLE portion of emulations is still too slow for LLE GPU. The same for LLE APU if we proceed. Only benefit we can gain is hybrid DirectX, or graphic, plugin and full LLE OHCI/USB. LLE APU isn't possible for a hybrid due to layer of classes.

**Comment by darkf** [comment]
I'm afraid I do not fully understand, what does using `__try` give us over using the equivalent `AddVectoredExceptionHandler` code? Can `AddVectoredExceptionHandler` not be used for error reporting too?

**Comment by RadWolfie** [comment]
> Meaning split exceptions into 2 different function to handle emu trigger (by VEH) and Cxbx faults (by SEH). For simplified and less false positive report.

`__try` is very bottom exception handler system which will forward to our error message system to inform testers/developers they need to fix "this" issue. Sometimes some exceptions can be ignore. 

Even rare exception occur is very helpful for give developers time to attach their debugger then click "cancel", or "ok"(?), from the popup window to enter the code's exception location within the debugger to troubleshoot the cause of the issue.

`AddVectoredExceptionHandler` is at the very top of exception handler system. There are drivers, such as graphic/audio, which will produce exceptions and are mostly false positive exceptions. `AddVectoredExceptionHandler` is only used for MMIO handler as I have explain in this post.

**Comment by LukeUsher** [comment]
@RadWolfie the problem could be solved by using AddVectoredExceptionHandler to register multiple handlers, not just one.

The first handler could be the fast mmio/rdtsc/privilaged instruction one, the second could be the fallback actual exception handler, then there would be no need to use __try/__except everywhere.

Vectored handlers are called in the order that they were added, so it should be a valid option.

**Comment by darkf** [comment]
I agree, there could be a catch-all handler in one place that doesn't need `__try`/`__except` everywhere.

Is there an easy way to trigger an error to test the reporting functionality?

**Comment by RadWolfie** [comment]
Do I understand __try/__except is a MSVC feature? Yes, plus `AddVectoredExceptionHandler` is a Windows feature and does not exist on other platforms (I had checked google search). Meaning we have to make a wrapper for other platform, yet still an easy task to do and require contributor to submit a pull request to support a platform we don't have access to.

Is there actually C standard exception handling implemented? Base on google search, there's none. Since C++ standard doesn't implement exceptions for such thing as division by zero error. If there is one, then please point it out.

I had been testing `AddVectoredExceptionHandler` function for first and last which give me better idea than the description is quite fuzzy to me. The doc for VEH is still quite incomplete for unknown reason.

FYI: VEH handles has top priority than SEH handles. So, this must be thoroughly tested to be sure any false positive did not occur.

**Comment by darkf** [comment]
@RadWolfie Do you plan on working on this, or should someone else look into it?

You're right that there is no standard exception support for those kinds of errors.

**Comment by RadWolfie** [comment]
I may will work on this since I can attempt to reproduce the issue base on previous pull request I had reported.

Depending on how busy the moving things around in the repository is. If everyone is busy working on their own end for a day or two. Then I will start work on it.

**Comment by PatrickvL** [comment]
Here some testing code that shows how `AddVectoredExceptionHandler` works in practice : https://docs.microsoft.com/en-us/windows/win32/debug/using-a-vectored-exception-handler

**Comment by RadWolfie** [comment]
While trying to replace SEH to VEH, I recently made discovery VEH is a global exception handler. Since there are per thread exception catch (SEH), we should consider start remove them in order to have error message popup correctly.

Also, I found an article describe how each exception handler is process.

https://docs.microsoft.com/en-us/archive/blogs/zhanli/c-tips-addvectoredexceptionhandler-addvectoredcontinuehandler-and-setunhandledexceptionfilter
> in my vectored exception filter `AddVectoredExceptionHandler, 1(CALL_FIRST)`
> in my filter ` __except(MyExceptFilter())`
> in my unhandled excepiton filter `SetUnhandledExceptionFilter`
> in my vectored continue handler `AddVectoredContinueHandler, 1(CALL_FIRST)`

Plus article claim VCH, vectored continue handler, will not be call since "Windows Error Reporting" gets involved for Windows 7. Unknown about Windows Vista OS.

**Comment by RadWolfie** [comment]
**UPDATE:**
While I have been replacing SEHs to allow VEH manage fatal crash. I encounter a demo title, Halo, show exception message for 2nd and later boots. When I click cancel, it continue on like nothing is happening and never made a crash. Plus unable catch the exception from Visual Studio.

After doing additional research. What I found in this doc: https://docs.microsoft.com/en-us/cpp/build/reference/eh-exception-handling-model?view=vs-2019#remarks
C++ exception handling ***is using SEH***.

I wonder if there's any chance to use `SetUnhandledExceptionFilter` function, since Wine support it.

**Comment by darkf** [comment]
> C++ exception handling is using SEH.

Only on MSVC. MinGW/gcc uses a different exception model, which is why things like that shouldn't be relied on.

I don't see why `SetUnhandledExceptionFilter` would be disallowed, if that helps you then go for it.
