### ISSUE TITLE
Deathrow Issue

### ISSUE THREAD

**Issue by jiangwei4** [Cxbx-Reloaded/Cxbx-Reloaded#1931]
## Quick summary
xbox backbuffer

## Details
When I try to launch deathrow I have this error : 
![image](https://user-images.githubusercontent.com/15106785/87680439-b9302100-c77d-11ea-9c88-11d27583a721.png)

### System Configuration:
 OS windows 10
 CPU I5-7300HQ
 GPU gtx 1070

### Additional Information (if any):
deathrow US 004 v1.03 :
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/4932419/Xbe.txt)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/4932420/KrnlDebug.txt)

**Comment by ergo720** [comment]
Still invalid because, like the template says, the GitHub Issue Tracker is not the place to ask for support or to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.

Your issue has been marked as **Invalid** and closed.
