### ISSUE TITLE
Releases & Trojan horse warnings

### ISSUE THREAD

**Issue by HuskyNator** [Cxbx-Reloaded/Cxbx-Reloaded#1959]
## Quick summary
Latest releases cause trojan horse warnings.

## Details
When uploaded to VirusTotal, the 'CxbxReloaded-Release-VS2019.zip' files of the latest 3 releases are detected by several engines as containing trojan horses.
Now i've seen there have been some false positives before, as such I'd like to ask how to know whether or not it is a false positive, and if know why this issue seems to be recurring.

### System Configuration:
* OS: Windows 10 Education
* CPU: intel i5-6600K
* GPU: GeForce GTX 1070

**Comment by Masamune3210** [comment]
For information, its due to the way that most modern anti-malware engines work, actually new never before seen files are rare in the computer world for the general populace, so anti-malware has taken the stance of treating it as malware until proven otherwise.
Unfortunately this causes headaches for anyone who deals with those files on the regular like programmers, archivists, and people who use bleeding edge builds like emulators and the like
Rarely is it actually anything substantial, basically just look around and see if multiple people have had the same issue

**Comment by PatrickvL** [comment]
That, and our loader may share some characteristics with malicious software, in that it loads an unknown executable into memory and jumps into the executable code of any and all game titles

**Comment by HuskyNator** [comment]
. . . I did follow the issue template as far as i know . _ . "

**Comment by ergo720** [comment]
You deleted the "Additional Information (if any):" paragraph, which is not optional and must be present. Also, this has already been reported in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1924, https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1571 and https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1225.

**Comment by PatrickvL** [comment]
Another thing that may be somewhat alarming towards heuristics based software analysis tools, is that our emulation code calls into a few low level kernel API's, which normal applications shouldn't do. We do that to avoid implementing a few of the more complicated parts of our own implementation of the Xbox kernel, by forwarding those parts to Windows NT kernel API's. Virus scanning might flag these calls as dangerous, and in some sense, they could indeed be dangerous, because when given the wrong arguments, those APIs could damage your Windows installation (small chance, but still).

**Comment by HuskyNator** [comment]
I dont feel like thats solved yet though @ergo720 . . . At least state in the readme or anywhere it's something thats recurring, if its not fixable. I personally prefer to be alerted beforehand of this before being stopped by windows from even moving files let alone running them . . .
