### ISSUE TITLE
Windows Defender detects cxbxr-debugger.exe as malware.

### ISSUE THREAD

**Issue by qeeg** [Cxbx-Reloaded/Cxbx-Reloaded#1963]
## Quick summary

Windows Defender detects cxbxr-debugger.exe as malware.

## Details

It's detected as Trojan:Win32/Wacatac.D6!ml

### System Configuration:

* OS
* CPU
* GPU
* etc.

OS: Windows 10 latest Insider Beta Channel preview.
CPU: Intel Core i3-3210
GPU: Geforce GTX 750Ti

**Comment by literalmente-game** [comment]
It's a false positive

**Comment by qeeg** [comment]
I know that, I'm just saying that there should be some action taken towards getting that rectified >.>

**Comment by literalmente-game** [comment]
No, the issue isn't the emulator, it's the software giving you a false negative. The only thing you can do to help is reporting that to Windows Defender

**Comment by qeeg** [comment]
I KNOW IT'S NOT THE EMULATOR. I'm just saying YOU GUYS should report the issue to Microsoft.

**Comment by Masamune3210** [comment]
The problem is you can report it until the heat death of the universe, it will just happen again the next time a new build is made. It's better to just note it as a false positive, and go on with your day

**Comment by RadWolfie** [comment]
@qeeg We had numerous of users on Cxbx-Reloaded discord asked about this same thing. There's nothing we, contributors, can do except report as false-positive on their own end. Our binaries are unsigned which lead to high chance of getting flagged as malware. Since they are nightly builds which contain changes every day. Even basic "hello world" project will trigger as malware too. Cheers
