### ISSUE TITLE
Black Screen Issue

### ISSUE THREAD

**Issue by Ed-Alarcon** [Cxbx-Reloaded/Cxbx-Reloaded#2017]
## Quick summary

I'm trying to use cxbx but everytime I run a game a black screen appears but the sound of the music of the game starts.

## Details

I'm trying to run Star Wars: Battlefront II and Matrix: The Path of Neo and any of them are working. I've tried all kinds of configurations

### System Configuration:

* OS
* CPU
* GPU
* etc.

I've tried of everything...

### Additional Information (if any):

I've seen a video that kind of explains how to solve it but still not working:

https://www.youtube.com/watch?v=c3jxUr2wTSs&t=8s

![Captura](https://user-images.githubusercontent.com/51338020/97497899-de156200-1930-11eb-9b6c-be4e7af242de.JPG)

**Comment by CakeLancelot** [comment]
Can you provide some information on your hardware? CPU, GPU, etc.?

**Comment by Ed-Alarcon** [comment]
I have a 
- HP 
- Windows 10 
- 4.00 GB (RAM)
- Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz 2.00GHz
- 64 bits , x64

**Comment by Ed-Alarcon** [comment]
> Can you provide some information on your hardware? CPU, GPU, etc.?

I have a

- HP
- Windows 10
- 4.00 GB (RAM)
- Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz 2.00GHz
- 64 bits , x64

**Comment by RadWolfie** [comment]
**Please read [the guidelines](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/README.md) and the [FAQ](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)) before opening an issue.**
 
Remember, Cxbx-Reloaded's issue tracker is not the place to submit [Game Compatibility](https://github.com/Cxbx-Reloaded/game-compatibility/blob/master/README.md) reports or ask for support. You must use our forum on [Discord](https://discord.gg/26Xjx23) for that.
 
Your issue has been marked as **Invalid** and will be close.

---

A link to youtube for Call of Duty: Finest Hour's black screen issue is irrelevant since it is always black screen due to FMVs are not render to screen. Plus both titles you mentioned are known not to work, search in Game Compatibility link above for details.
