### ISSUE TITLE
Broken animations and bad lighting in Midnight Club 3 dub edition remix

### ISSUE THREAD

**Issue by mamcocob64** [Cxbx-Reloaded/Cxbx-Reloaded#2303]
I know Cxbx Reloaded is still young outta the whom but I want the developers to be aware of midnight club 3's most scary bug. the animations used for pedestrians and race starters are not working correctly. They hop around like pogo sticks as if they are stuck in the t-pose when they were modeled. I put in PCSX2 for comparison because I want to show you what it's supposed to look like

https://user-images.githubusercontent.com/40497987/147625036-8624faed-afcc-419e-a7cd-af08f710a7dc.mp4

**Comment by PatrickvL** [comment]
The bot is correct but if you're planning to resubmit your issue, first search for both topics whether an issue already exists (in which case just add a comment there that your title version so and so has the same issue). Otherwise split up in separate issues and Do follow the template. Thank you.

**Comment by mamcocob64** [comment]
I wish it was easy. I just want to report this issue easily. What kind of
stupid template are you talking about? I just flatout want to report issues
and have my complaints and suggestions heard. You don't need a template for
a police report or a 911 emergency do you? it's confusing as fucking hell

**Comment by PatrickvL** [comment]
Language....

**Comment by Masamune3210** [comment]
The template is there to make it easier on maintainers , most if not all of whom work on this of their own volition and aren't paid for it. It is automatically in the box when you make a issue but unfortunately people tend to just blow it away and write whatever

Ironically enough you do in fact need a template to make a 911 or police call, the template is just in the form of questions asked rather than manually filled out ahead of time

**Comment by PatrickvL** [comment]
Yeah, the thing is, we currently can't really act on generic "X doesn't work right" reports - if we would accept such issues, we would soon get swamped in them, as there's bound to be hundreds of things currently not working right. (I did like the comparison video, though, so that was not wasted, not on me at least, heh.)

Also, it's good to know that there's not many people working on this, and time is sparse for most of us that are contributing. Right now, we're focusing on kernel accuracy, sound is also being worked on, but graphics not so much. We'll get to it later, I'm sure. Let's keep this issue closed for now, and wait until improvements are submitted at some point that will not only fix this issue, but many others as well.
