### ISSUE TITLE
Buffy the vampire slayer Issues

### ISSUE THREAD

**Issue by kanelakis** [Cxbx-Reloaded/Cxbx-Reloaded#241]
Hi, I want to play but Buffy gets an error message, how can I fix it?

**Comment by LukeUsher** [comment]
The emulator is not developed enough to play this game yet. In a previous commit, a long time ago, it was possible to get the intro to play, but even this was unstable and didn't happen 100% of the time. 

In the current state, most games do nothing, some show menus and a tiny handful get in-game, despite years of development, this emulator is still in the beginning stages.

This is a game I want to get working myself, but it is likely to be a long time away from now before it is playable.

**Comment by kanelakis** [comment]
Ok, thanks for the reply.
I hope with all my heart that this emulator functions soon.
Keep working to make this possible.

**Comment by BenNottelling** [comment]
@kanelakis You can help by testing the game with every new build and reporting on errors you get :D

**Comment by kanelakis** [comment]
I do not play to test the emulator, I would serve the sources where obtain them and test them.

**Comment by BenNottelling** [comment]
@kanelakis to obtain and test what?

**Comment by kanelakis** [comment]
Sorry, I misunderstood the answer.

**Comment by BenNottelling** [comment]
@kanelakis Ah, OK

**Comment by PatrickvL** [comment]
@kanelakis Please add more details to this report, like log files and screenshots (if anything is shown)

**Comment by kanelakis** [comment]
Ok, I will send the error as soon as I can and image.

**Comment by kanelakis** [comment]
[URL=http://www.imagebam.com/image/a48ab3541110252][IMG]http://thumbnails101.imagebam.com/54112/a48ab3541110252.jpg[/IMG][/URL]

**Comment by BiatuAutMiahn** [comment]
@kanelakis, That's a pretty old version, a lot of changes have been made since then

**Comment by kanelakis** [comment]
Please send me a new version of emulator.

**Comment by PatrickvL** [comment]
That looks like an old build, recently there have been some improvements, your could try the latest

**Comment by kanelakis** [comment]
Even for the game Gladius?

**Comment by kanelakis** [comment]
I downloaded your version Reloaded master, but it appears the same mistake.
however, if the emulator and still in the works, expect a release that you can test with the game.

**Comment by ObiKKa** [comment]
In Hardware Video the intro logo movie (Fox Studios) was flickering on a white screen, but can see it even less than in Battlestar Galactica (Also harder to see in non-Hardware Video mode). There's a KeBugCheck error message to get past with either Hardware Video mode on or off. Then you enter the main menu.

![2017-apr-13_first-test _intro-logo-movie](https://cloud.githubusercontent.com/assets/18428108/25003620/aac1bf5a-2093-11e7-8f19-6c4881e71333.png)
![2017-apr-13_first-test _crash](https://cloud.githubusercontent.com/assets/18428108/25003623/ae1fdcf4-2093-11e7-95e1-62fb91a9dee7.png)

* One problem: After my first time entering a start game screen or getting into the game on later retries the emulator would remember the save file(s) for the game so I cannot 'Start' a new game. Instead I have to go to the Load game screen. Where are the files that need to be deleted in order to enable a fresh start on later boots?
* I also struggled really hard to force selection in the main menu to move down below the top-most 'Start Game' option as it'd just return back there quickly. So I had to hold down the down key for the left analog nub (D-Pad buttons do not even work in this game) and then press on the Load Game option to start a game.
On the first boot or first few tries I could move up and down the main menu's options just fine. But no longer.
* Also if you linger around in the menus for a bit too long then a different error message cautioning too many active threads going on will appear and stop the game.

The title screen and main menu have kinda garbled rendering. Ingame GFX corruption is **very** bad. But you can see the in-game menus fine. Another KeBugCheck error message also popped up during the loading screen with a movie leading to the in-game world - got past it too.

![2017-apr-13_first-test _01_title-screen](https://cloud.githubusercontent.com/assets/18428108/25003692/10045526-2094-11e7-88ff-301d43016fa9.png)
![2017-apr-13_first-test _02_main-menu](https://cloud.githubusercontent.com/assets/18428108/25003693/100bbf96-2094-11e7-96b5-77ed8ee11cc4.png)
![2017-apr-13_first-test _03_lingering-error](https://cloud.githubusercontent.com/assets/18428108/25003694/100dac66-2094-11e7-9542-2e804c2474c0.png)
![2017-apr-13_first-test _04_save-file-inaccess](https://cloud.githubusercontent.com/assets/18428108/25003695/100e2bbe-2094-11e7-920f-8fff4f187120.png)
![2017-apr-13_first-test _05_load-game-screen](https://cloud.githubusercontent.com/assets/18428108/25003696/10125c52-2094-11e7-80e0-31141c292de6.png)
![2017-apr-13_first-test _06_error-during-ingame-loading](https://cloud.githubusercontent.com/assets/18428108/25003712/236e3d34-2094-11e7-9548-3b9bddee3a81.png)
![2017-apr-13_first-test _07_start-ingame](https://cloud.githubusercontent.com/assets/18428108/25003711/236cebb4-2094-11e7-8261-567a438aba1a.png)
![2017-apr-13_first-test _08_ingame-corruption](https://cloud.githubusercontent.com/assets/18428108/25003713/23736872-2094-11e7-9301-9b9eaa10ccaf.png)

Had a huge problem trimming down the fat in the Kernel document from 45MB to 5MB because the intros and controlling the menu and then entering the game took so long!
[Xbe_(2017-04-13).txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/919410/Xbe_.2017-04-13.txt)
[KrnlDebug_(2017-04-13)_Trimmed.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/919411/KrnlDebug_.2017-04-13._Trimmed.txt)

**Comment by kanelakis** [comment]
Which settings you used to do to start?
I like the characteristics of the PC:
Intel Core i7 3770 3.40 GHz
Ram: 16 gb
Nvidia Geforce 1060 GTX 6 gb

**Comment by ObiKKa** [comment]
First two screenshots above are from Hardware Video mode. All the rest are with that mode turned off because you cannot continue in Video mode after that KeBugCheck error message pops up. The secondary screen just freezes in black only.
My specs:
OS: Win 7 Ultimate 64 bit
CPU: Intel Core i5-2500k @3.3GHz (3.60GHz Turbo)
RAM: 8 GB
GPU: GeForce GTX 750 Ti 2 GB

**Comment by kanelakis** [comment]
I only get the error message in the previous post. I should know which configurations to set up.

**Comment by blueshogun96** [comment]
I have Buffy but it never shows any of this for me.  I'll grab the latest build and try again.  

Shogun

**Comment by kanelakis** [comment]
http://www.imagebam.com/image/7d635a543294484
I took the latest version, as you see it does the same thing.
Whether it's hardwere or software.

**Comment by kanelakis** [comment]
http://www.imagebam.com/image/f6315c543296513
http://www.imagebam.com/image/c2a72d543296512
I did a test, I removed the experimental options, another message appeared to me.

**Comment by ObiKKa** [comment]
It worked for me again like above in the latest pending PR (number 367). Leave the three option boxes (Hardware Video mode, Force V-Sync, Enable Hardware YUV Overlays) unchecked in the Video Config window.
My second drop-down selection (Direct3D Device) is set to Direct3D HAL (Hardware Accelerated); and third selection (Video Resolution) is set to Automatic (Default).

**Comment by kanelakis** [comment]
I did other tests, the error message disappeared, I can put the full-screen resolution only with resolutions of: 1280x1024 25 fps, but the screen is small. The screaming sound, and I tried to make the configuration with the controller For Xbox 360, but after a while, if I press the buttons or the nickname is over, the message appears.

**Comment by kanelakis** [comment]
I used a Pal version EU

**Comment by kanelakis** [comment]
http://www.imagebam.com/image/c6076c543302846
http://www.imagebam.com/image/7210de543303807
These are the configurations where the movie starts and then stops giving the message.

**Comment by kanelakis** [comment]
I send the video if is possible

**Comment by kanelakis** [comment]
I used this configuration Butterfly-white,and the screen butterfly-white,after them giving the message.

**Comment by ObiKKa** [comment]
After PR #370 including a number of jaruppx's OOVPA consolidation fixes and the un-pulled libyuv video playback commits from Patrick (I think it's in) I booted up the latest master build and forgot that I already had left the D3D device in REF, software option when I tested another game on an older build.
So there and then I saw all the movies of this game playing beautifully with no flicker. But I cannot get into the menu nor game - only in Hardware Accelerated option can you do that.

However see that the Fox logo video has a dark, thin bar on the left side. Maybe it's not a glitch.
![2017-apr-13_2nd-test _01_title](https://cloud.githubusercontent.com/assets/18428108/25054753/54c15bc8-21a2-11e7-8fc5-30ff6575fffd.png)
![2017-apr-13_2nd-test _02_ea-logo](https://cloud.githubusercontent.com/assets/18428108/25054752/54bee078-21a2-11e7-9755-399c42635918.png)
![2017-apr-13_2nd-test _03_fox-logo](https://cloud.githubusercontent.com/assets/18428108/25054754/54c384ac-21a2-11e7-84b1-f0b5798785e6.png)
![2017-apr-13_2nd-test _04_dev-logo](https://cloud.githubusercontent.com/assets/18428108/25054757/54da24b4-21a2-11e7-9f61-d0ccc9c735ed.png)
![2017-apr-13_2nd-test _05_intro-cutscene](https://cloud.githubusercontent.com/assets/18428108/25054756/54c83092-21a2-11e7-8dab-5611ccdedb51.png)
![2017-apr-13_2nd-test _06_cutscene-title](https://cloud.githubusercontent.com/assets/18428108/25054755/54c84e2e-21a2-11e7-9989-5ecce7655617.png)
![2017-apr-13_2nd-test _07_crash-after-movies](https://cloud.githubusercontent.com/assets/18428108/25054758/54f365e6-21a2-11e7-8271-58e865ba9258.png)

kanelakis, I think your experience may be normal. I got in-game with the latest build described here, but then now cannot do that in the old build (2 days ago) numbered far above anymore due to an exception code error, weird. But I can get in-game on another build in-between or the day after my first build test up here!

[KrnlDebug_(2017-04-15_D3D_REF-Software)_Trimmed.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/922902/KrnlDebug_.2017-04-15_D3D_REF-Software._Trimmed.txt)

**Comment by kanelakis** [comment]
I now have the new version of the 14, the problem I have with the same, without changing the options.

**Comment by ObiKKa** [comment]
Unfortunately after those couple of video improvement PRs (#365 & #367) a crash message immediately popped up as soon as the game finished loading the in-game world.
* The D-Pad movement controls now seem to control the menu options, not just the left analog stick like before.

![2017-apr-16 _ingame-crash](https://cloud.githubusercontent.com/assets/18428108/25069629/2fe2f8f6-22ca-11e7-8559-1c10fd4f28ba.png)
[KrnlDebug_(2017-04-16_Two-video-PRs).txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/924137/KrnlDebug_.2017-04-16_Two-video-PRs.txt)

**Comment by kanelakis** [comment]
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/928071/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/928072/KrnlDebug.txt)
Here debug files.

**Comment by kanelakis** [comment]
I also tested the US version, with the same settings, the usual PAL message message arrives.
I attach debug files.
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/945620/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/945621/KrnlDebug.txt)

**Comment by ObiKKa** [comment]
Hmm. 1st try: Could see the early intros a bit more often though they do flicker (Perhaps thanks to PR #383 [Overlay fixes]. And went in the menu again I think then loading before crash like recently.
2nd and 3rd tries: I now see that the purple haze/fog in the main menu and other menus now appear to be pixelated and not as detailed/sharp as before. That's strange. Also on whatever text option that is selected the words are now split into two in a 'shadowed' fashion - one off diagonally behind the front text. Look here below. I think those were issues arising from the HLE caching implementation (PR #384).

![collage-2017-04-21](https://cloud.githubusercontent.com/assets/18428108/25255600/d10ea980-266e-11e7-8a1f-e851b83efe7b.png)

**Comment by kanelakis** [comment]
In the second image, maybe an incorrect text option was selected,

**Comment by kanelakis** [comment]
Pal Version
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/963234/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/963237/KrnlDebug.txt)
Usa Version
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/963239/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/963240/KrnlDebug.txt)
In both versions the message I first reported does not appear anymore, now after the initials remain with the fixed black screen.

**Comment by kanelakis** [comment]
A new error message appears.
http://www.imagebam.com/image/dc5b76546490964
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/974815/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/974816/KrnlDebug.txt)
It happens to me with both versions of the game.
It happens to me right away, as soon as I start the game.

**Comment by kanelakis** [comment]
http://www.imagebam.com/image/59e551548881419
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1005887/CxbxDebug.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1005888/KrnlDebug.txt)
Anoder error.

**Comment by cybertronicgames** [comment]
[Title ID 45410012] Buffy The Vampire Slayer was working on CXBX-Reloaded 98b86c8 (Apr 14, 2017)
![screenshot 18](https://user-images.githubusercontent.com/14711758/28992399-5273f3ba-7960-11e7-8e55-088c4976822e.png)
This game was working on build version CXBX-Reloaded 98b86c8a (Apr 14, 2017), The Xinput controller didn't work on any games so, I couldn't start the game. 
https://www.youtube.com/watch?v=uLW0qXI65Gc
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1202060/Xbe.txt)

**Comment by kanelakis** [comment]
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1239732/KrnlDebug.txt)
With the August 21 release the game gives me the same mistake as the previous post.
[CxbxDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1239730/CxbxDebug.txt)

**Comment by PatrickvL** [comment]
This issue has outgrown it's usefulness, as it doesn't really describe one single concrete issue anymore. Game specific reports should be made in the game compatibility tracker nowadays. Closing this.
