### ISSUE TITLE
Inlined D3DDevice_BlockUntilVerticalBlank needs emulation without patching

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#2419]
## Quick summary

Titles where D3DDevice_BlockUntilVerticalBlank is both present as-is, but also inlined cannot patch the latter (since functions are only detected in one location by the symbol scanning code).

Therefore, this function has to be emulated without resorting to patching.

## Details

See corresponding (now closed) issue in the symbol scanning project.

Test case : Black

### System Configuration:

* OS
* CPU
* GPU
* etc.

**Comment by RadWolfie** [comment]
Unpatching D3DDevice_BlockUntilVerticalBlank function had been implemented in a wip branch. However, it absolutely require PTIMER from nv2a implement, upstream didn't have fully implemented, in order to support PAL50 mode with titles compiled from XDK 4627 and above. A test case for missing PAL50 mode support that cause dirty disc error is Dead or Alive Ultimate disc number 2.

**Comment by ergo720** [comment]
This was done in 3515449200a2df220f061105c5a24bf97ae7dc1e, which merged my `less_busy_loop` branch (which implemented all of the above)), so closing this.
