### ISSUE TITLE
DEAD OR ALIVE 2 ULTIMATE

### ISSUE THREAD

**Issue by kekshina** [Cxbx-Reloaded/Cxbx-Reloaded#2431]
## Quick summary
All of the stages show a full white screen
or crashes and plays a very glichy sound
On the latest build 
### System Configuration:

* OS WIN 11
* CPU 11th GEN INTEL i5
* GPU GTX 1660 SUPER
* etc. 16 GB RAM

### Additional Information (if any):

![Screenshot 2023-09-15 161821](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/assets/145164132/42c18623-7f2a-4655-b199-ae5d442e48ed)

https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/assets/145164132/7251903f-ab3b-41a5-8f69-8cbb960c6f4c

**Comment by kekshina** [comment]
I see vids where this game is perfect so i dont get why its glichy for me

**Comment by RadWolfie** [comment]
Hi @kekshina, you may want to check those videos to obtain specific build from using [releases](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/releases) page's search bar. In order to receive possible expected result from those videos on your end.

Your system configuration indeed do meet the minimal requirement. Yet do expect some performance drop here and there as usual. Even possible graphic glitches too. Cxbx-Reloaded is still in experimental stage.

If the issue still persistent on the same build as from videos. Then it could be graphic card or the driver issue.
