### ISSUE TITLE
Remove all unnecessary patches

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#25]
Any patch that's currently present just because it originally called unimplemented kernel functions, can be removed once the kernel functions it calls are all present and implemented far enough to be usable.

After this is done, all that's left will be patches over code that accesses hardware and/or still unimplemented kernel functions.

**Comment by LukeUsher** [comment]
Keep in mind that until we implement NV2A emulation, there are some Direct3D patches we cannot remove even though they do not access any hardware, doc/Direct3D.txt explains the reasoning for this:

"Direct3D resources are going to be a little bit of a hack.
There is a tough situation, because precompiled resources
(XPR) can be loaded into memory manually by an Xbox Game,
and then "Registered" with pResource->Register(addr);

This is a problem because we never have an opportunity to
intercept the "this" pointer for this datatype. The base
resource class looks like this:

DWORD Common;
DWORD Data;
DWORD Lock;

The first idea is to tuck away the PC Direct3D resource
pointer inside of pResource->Data. The trouble with this
is that some Xbox Games will directly access and modify
this member.

Another technique is to hide the PC Direct3D resource pointer
inside of the buffer allocated by Data. This could work, as
long as Xbox Games do not access the resource Data after the
initial Register function is called.

The currently used method is to tuck the pointer away inside
of the Lock member, and hijack any functions that attempt to
access the Lock member variable."

**Comment by PatrickvL** [comment]
I've been making some progress on this. Once that's merged, we might as well close this issue, as we're indeed not going to remove patches that depend on one another, like in D3D8 and DSOUND.

When LLE is enabled for APU and/or GPU, we now skip the related part of the OOVPA database.

But when LLE is disable we still use these OOVPA's, so we'll keep those around until LLE is on par or better than the patch based approach.

**Comment by PatrickvL** [comment]
I agree that HLE sound and video requires patches that don't actually call kernel functions or address hardware. We should keep those around until we drop HLE.
However, patches which just rely on kernel functions and do not address hardware, can be removed once the kernel had matured enough to run these code fragments unpatched. 

As far as I've seen, the current code base doesn't contain unnecessary patches anymore, so we might as well closing this issue.
