### ISSUE TITLE
Allow 30FPS VSYNC? 

### ISSUE THREAD

**Issue by BenNottelling** [Cxbx-Reloaded/Cxbx-Reloaded#261]
Currently enabling VSYNC locks the FPS to 60, which it great for games that run at such speeds, but with games that run at 30FPS they then run at twice the speed intended, making it almost unplayable (like Turok). I propose that an option to lock games to 30FPS or 60FPS would be a much better solution.

(Even if it locks to you VSYNC of your monitor as VSYNC is supposed to 30FPS doesn't work on modern screens and actually requires a CRT meaning setting a virtual refresh rate won't work as well)

**Comment by LukeUsher** [comment]
I understand the need for this but it likely won't be implemented. As the emulation gets more accurate hacks like this are becoming less needed, I'd like to avoid adding more hacks like this and work on improving emulation so they are no longer needed

**Comment by PatrickvL** [comment]
There's more to consider; some software might use different refresh rates for different phases, and there's the difference between ntsc and pal titles, plus what would happen when running those on opposing systems

**Comment by LukeUsher** [comment]
PAL vs NTSC isn't a big deal on the Xbox hardware, all video modes are supported on both, the only difference is a PAL setting in the EEPROM disables HD resolutions. The games themselves run exactly the same on both configurations

**Comment by PatrickvL** [comment]
So you're saying that all Xboxes support both NTSC and PAL, and they're not build region-specifically?
If so, then what about the current they're fed by - doesn't that influence their timers? Or is all that compensated somewhere?

And about the video output;
What if a 50 Hz PAL signal is send to a 60 Hz NTSC CRT, and vice versa (60 Hz to a 50 Hz PAL CRT)?
And what about LCD and/or other display devices that use a refresh rate different from the signal the Xbox supplies?

We should figure this stuff out and describe it somewhere.

**Comment by LukeUsher** [comment]
Timers are not effected by input current at all, in most systems this is also the case. Display output is usually linked to the video encoder, which in the Xbox case is fully configurable in software (output resolution, frequency, etc)

As for TVs, most made since the early 2000s are compatible with both 50hz and 60hz, if the TV doesn't support it, you'll either get incorrect colours or no working VSYNC (rolling picture).

**Comment by LukeUsher** [comment]
Figured out how timing is determined, at least as far as D3D is concerned.

Within Direct3D, if AV_FLAGS_60Hz is set, VSYNC is assumed to be 60hz, otherwise 50hz. 
The games that are running too fast with VSYNC must be relying on something other than D3D's VSYNC timing, this needs investigation to discover specifically what these titles are doing for timing.

**Comment by bhodg22** [comment]
JSRF runs too fast with the current VSYNC

**Comment by LukeUsher** [comment]
Closing this as we will not implement 30FPS VSync, instead we will work on improving emulation accuracy, and eventually, we will use the correct VBlank timing.
