### ISSUE TITLE
Robotech Battlecry goes in game with some broken graphics

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#277]
Robotech Battlecry goes ingame with some broken graphics and missed intros and some videos
![screenshot_9](https://cloud.githubusercontent.com/assets/25540784/24326983/f8458d7c-11fe-11e7-9127-a3f03345007b.png)
![screenshot_10](https://cloud.githubusercontent.com/assets/25540784/24326981/f843ea30-11fe-11e7-8ecc-84d18cf9ca1d.png)
![screenshot_11](https://cloud.githubusercontent.com/assets/25540784/24326979/f84390c6-11fe-11e7-8f90-6942f2a90c4f.png)
![screenshot_12](https://cloud.githubusercontent.com/assets/25540784/24326982/f8443dc8-11fe-11e7-87bc-2da47995b6aa.png)
![screenshot_13](https://cloud.githubusercontent.com/assets/25540784/24326980/f843d266-11fe-11e7-8a6d-7aac1d2cfd0f.png)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/870448/Xbe.txt)
Sorry, i have not able to attach KrnlDebug.txt beacause it reaches about 221 mb

**Comment by blueshogun96** [comment]
Okay, the reason this happens is because there is a bug in Cxbx's vertex data patching code somewhere.  Revel8n and I worked together on this with Cxbx years ago and we came up with a fix to skip the rendering of the skydome.  If you can make it to level 3, this issue does not come up.

For a specific explanation here, consider the code in D3DDevice_DrawIndexedVertices and look at the Vertex patching code (see https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/src/CxbxKrnl/EmuD3D8.cpp#L7911).  There's a bug where this code fails and causes the emulator to crash when the data is sent through the pipeline.  I forgot exactly what we were thinking at the time, but I wrote a quick workaround to avoid the crash as there was no valid vertex buffer data to patch.  There's likely a *much* better way to fix this, I just didn't think of anything else at the time.  Because of Cxbx's design, it was kinda hard for me to debug it.

Hopefully that sheds some light on the issue.

Shogun

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#168
