### ISSUE TITLE
Configure Controller Bugs

### ISSUE THREAD

**Issue by BiatuAutMiahn** [Cxbx-Reloaded/Cxbx-Reloaded#28]
When configuring the controller i notice 2 things

1. The D-Pad or is not recognised on an Xbox 360 controller.
2. When using configure all inputs option, Escape fails to exit the process properly causing a loop where the last un-entered key is prompted for input.

I would not consider this a priority as i know more xbox-related work is needed

**Comment by LukeUsher** [comment]
The first issue is because Cxbx is very old, it was created before XInput was a thing on PCs so still uses the legacy DirectInput API. 

The second is actually a bug, but not priority at all.  There will probably be a new GUI at some point because as we implement more functionality we will need a better configuration system, so this will probably be addressed way in the future when that happens.

**Comment by AzurikRiseOfPerathia** [comment]
I think that will make the Xbox Original controllers compatible. I have the adapter that goes with it. Because I was able to put XDCT that allows to cofigure the controller, suddenly the controller does not work on the cxbx emulator

**Comment by CommanderChef** [comment]
I'm using a PS2 Controller on a USB Adapter I bought for my PS3, My D-Pad is not working, Buttons and Analog and Triggers are working as I config them, but not in-game.

**Comment by ergo720** [comment]
Closing this, as with the [new input GUI](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1713) xbox 360 controllers will always use XInput and the D-Pad works for them. The other was a bug of the old input GUI, which was completely removed so it's no longer an issue now.
