### ISSUE TITLE
Whacked! - in-game but has buggy graphics and breaks instantly

### ISSUE THREAD

**Issue by furrya** [Cxbx-Reloaded/Cxbx-Reloaded#297]
Whacked! - almost reaches the menu, but breaks down with the 
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/882759/KrnlDebug.txt)
exception code regression
![screenshot_11](https://cloud.githubusercontent.com/assets/25540784/24509818/603c492e-15a2-11e7-989b-90ed74db397f.png)
![screenshot_13](https://cloud.githubusercontent.com/assets/25540784/24509817/603b6fc2-15a2-11e7-8d59-4e2ba3d0a380.png)

[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/978089/Xbe.txt)

**Comment by PatrickvL** [comment]
According to @furrya, previously, after laggy and broken intro screens the title (Menu) appeared and momentally resets without any errors.

**Comment by furrya** [comment]
Cxbx-Reloaded Version 394aee6b (Apr 29 2017)

Whacked! - in-game but has buggy graphics and breaks instantly. Also the intro videos are broken
_____________________________________________________________
![screenshot_1](https://cloud.githubusercontent.com/assets/25540784/25560668/d6445a0c-2d95-11e7-9eb4-50fb62e08e78.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/25540784/25560664/d641c990-2d95-11e7-8c2c-940e34ce69d0.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/25540784/25560667/d643ceac-2d95-11e7-950d-2ebca9d8a796.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/25540784/25560665/d6429e2e-2d95-11e7-94fa-ee96a0d6297e.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/25540784/25560669/d647c02a-2d95-11e7-9ab0-ca02f8465c13.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/25540784/25560666/d64330d2-2d95-11e7-9d77-6ed5f30385e7.png)
__________________________________________________________
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/966521/KrnlDebug.txt)

**Comment by ObiKKa** [comment]
Whoa. These are some lovely graphics (for now)! But thankfully a model there was censored by lucky emulation glitches! o__o

**Comment by blueshogun96** [comment]
Is that PAL, NTSC, or NTSC-J?  My old Cxbx branch had similar problems but they were different per region.  I have a physical copy of NTSC-M and NTSC-J, none of them work for me.  They just crash on the menu.

I'm very interested in this game because not only is it my 3rd favourite Xbox game, but because it supports Xbox Live.  I've been wanting to find out if it were at all possible to HLE Xbox Live for quite some time, but lack of a 32-bit OS for my old Cxbx branch prevented me from experimenting with this.  If this will ever work for me, then I will put some effort into that and see if it's at all possible.

Shogun

**Comment by furrya** [comment]
@blueshogun96 The version of the game  / Whacked! - NTSC US -  XDK 4831 version.  One screen from DXBX are below . I hope it´s help  .
![image](https://cloud.githubusercontent.com/assets/25540784/25733168/77ed3258-3191-11e7-9089-2b26c5f0c379.png)

**Comment by blueshogun96** [comment]
Yeah, I already have that information.  Tried the NTSC-J and US version, still crashes promptly at the menus.  I just don't understand why it works for you but not for me.  Oh well.

Shogun.

**Comment by furrya** [comment]
@blueshogun96 Probably there are still some minor differences. Hmm.
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/978088/Xbe.txt)

**Comment by blueshogun96** [comment]
The region code is different than the ones I have.  Odd.

Shogun

**Comment by LukeUsher** [comment]
There are usually different variations of region codes, and to make matters worse, a lot of ripping tools (DVD2Xbox, UnleashX, etc) apply patches on copy that alter the XBE's region and add anti-piracy patches. We recommend unmodified Xbe's are used, because we cannot be sure what modifications have been made or be sure of exactly what version a title is, if it has been modified.

Try uploading the XBE to my old Compatibility List: http://cxbx-reloaded.co.uk/compatibility
It will be accepted if it's a valid XBE, or rejected if it's been modified/patched.

**Comment by blueshogun96** [comment]
Okay, didn't know that.  Personally I use my green debug Xbox to dump files though Xbox Neighbourhood as I find that to be much easier.  Although I did notice the region code to be incorrect on one .xbe so maybe I did screw something up somewhere.

Shogun

**Comment by furrya** [comment]
There is some xbox title ids database http://www.xbox-games.org/
