### ISSUE TITLE
Cleanup OOVPA Tables

### ISSUE THREAD

**Issue by LukeUsher** [Cxbx-Reloaded/Cxbx-Reloaded#34]
The OOVPA tables in their current form are very prone to errors.
The definition of symbols should be simplified via Macros to reduce the chance of mistakes.

**Comment by PatrickvL** [comment]
I've been busy with this already, better wait for that...

**Comment by LukeUsher** [comment]
If you're already working on this I'll assign it to you ->All I did so far was implement the exact same example as per that ngemu thread, from the sounds of it you're already further than that.

**Comment by PatrickvL** [comment]
Yeah, that code was just a prove of concept. I've been getting "production ready" so to speak

**Comment by PatrickvL** [comment]
I tried getting rid of the Count field in the OOVPA declarations, but encountered a problem;

The standard doesn't seem to support Variable Length Array (VLA) declarations inside a template, since I when I declare `Sopv `and `Lopv `as `[]`, get :
> Warning	C4200	nonstandard extension used: zero-sized array in struct/union	CxbxKrnl	d:\patrick\git\cxbx-reloaded\src\cxbxkrnl\OOVPA.h	90	

Also, reading the size using `sizeof(Loovpa->Lovp)` errors with :
> Error	C2070	'LOOVPA<1>::LOVP []': illegal sizeof operand	CxbxKrnl	D:\Patrick\git\Cxbx-Reloaded\src\CxbxKrnl\HLEIntercept.cpp	598	

So, we'll need to keep the Count for now.

**Comment by LukeUsher** [comment]
Okay, could probably put together a solution using a std::vector rather than an array, that keeps track of size. I used that in EmuFS to store the search patterns. Keep using arrays and count for now. I'll have a look into this myself afterwards

**Comment by PatrickvL** [comment]
It's 2528 OOVPA_TABLE_ENTRY's to refactor. I've applied lots of global find-replaces using Notepad++ to transform many code, but there's still a lot of manual labor left to do. But I'll just subbornly keep going on until it's finished.

**Comment by PatrickvL** [comment]
I've got a completely other idea too, but that can only be done once this transform is done.

The idea is, to redefine the macro's into registration calls, so that the entire datastructure can be put into a trie, much like I implemented in Dxbx.
Search patterns using a trie can be much faster than the current approach, plus it would allow me to prevent collisions (when patterns overlapping).

**Comment by PatrickvL** [comment]
Current macro's I'm working with :
```
#define OOVPA_XREF_LARGE(Name, Count, XRefSaveIndex, XRefCount)	\
LOOVPA<Count> Name = { { /*OOVPAType*/Large, Count, XRefSaveIndex, XRefCount }, {

#define OOVPA_XREF(Name, Count, XRefSaveIndex, XRefCount)	\
SOOVPA<Count> Name = { { /*OOVPAType*/Small, Count, XRefSaveIndex, XRefCount }, {

#define OOVPA_NO_XREF_LARGE(Name, Count) \
OOVPA_XREF_LARGE(Name, Count, XRefNotSaved, XRefNotUsed)

#define OOVPA_NO_XREF(Name, Count) \
OOVPA_XREF(Name, Count, XRefNotSaved, XRefNotUsed)

#define OOVPA_ENTRY(Offset, Value) { Offset, Value },
#define OOVPA_END } }


#if _DEBUG_TRACE
#define OOVPA_TABLE_ENTRY(oovpa_def, cxbx_def)	\
	{&oovpa_def.Header, cxbx_def, #cxbx_def}
#define OOVPA_TABLE_XREF_ENTRY(oovpa_def, cxbx_def)	\
	{&oovpa_def.Header, 0, #cxbx_def}
#else
#define OOVPA_TABLE_ENTRY(oovpa_def, cxbx_def)	\
	{&oovpa_def.Header, cxbx_def}
#define OOVPA_TABLE_XREF_ENTRY(oovpa_def, cxbx_def)	\
	{&oovpa_def.Header, 0}
#endif

```
