### ISSUE TITLE
Panzer Dragoon ORTA [Demo & Retail]: Ingame again

### ISSUE THREAD

**Issue by blueshogun96** [Cxbx-Reloaded/Cxbx-Reloaded#418]
Since @PatrickvL continuously urged me to get some code submitted, I spent all afternoon and evening working on this to make up for what I left unfinished (you guys inherited my mess, sorry about that).

![cxbx 2017-05-01 22-47-06-04](https://cloud.githubusercontent.com/assets/5076651/25610391/e0b9e900-2ed7-11e7-8bef-e53f5da077e8.png)

![cxbx 2017-05-01 22-47-44-81](https://cloud.githubusercontent.com/assets/5076651/25610399/e5ac385a-2ed7-11e7-947f-337058db1779.png)

![cxbx 2017-05-02 01-12-35-49](https://cloud.githubusercontent.com/assets/5076651/25610405/ec2adfe2-2ed7-11e7-89ac-b8cdfcd9da18.png)

![cxbx 2017-05-02 01-25-20-55](https://cloud.githubusercontent.com/assets/5076651/25610411/f1f2f004-2ed7-11e7-9df9-b1ab3c8848ca.png)

I wanted to make a few comments on these, as I feel it to be necessary.  There was a bug in NtCreateEvent's implementation causing the most important event handle never to get created in the first place, causing the game to hang infinitely when you try to select anything in the menus.  Since Microsoft was too lazy to error check several driver level APIs (and possibly kernel APIs too), this error was never handled by the OS and hence why in the past this game only worked on Vista (I'll blog about it later; it's a LONG story).  I also did a quick texture related hack since X1R5G5B5 formatted textures don't seem to be supported for me and it worked again!  Funny how the issue I've been chasing years back suddenly became obvious.

Now, the 3rd image comes from the PD Demo, and the 4th comes from the final released game.  I wasn't able to get into episode one for the retail because the game hangs when it tries to play an FMV.  No idea why it hangs yet.  The demo doesn't have a video to play so it goes ingame with minimal issues.  The retail version only allows me to get into the tutorials.  In either case, the sound buffer cache fills up rather quickly so you can't play it for very long.  Also keep in mind that this game has some of the same visual artifiacts that Turok has (most notably that stencil-like bug) so it's good to keep it in mind.

Lastly, I wanted to state that once again you guys are doing a terrific job.  Luke clearly managed to fix the broken geometry issue this game has been suffering from.  I'll be submitting a pull request in a moment.  Keep up the good work guys.

Shogun

**Comment by blueshogun96** [comment]
http://ngemu.com/threads/svn-rev-159-vs-153-and-panzer-dragoon-orta.134298/

I wanted to reference this thread on ngemu, as StrikerX3 has mentioned some things that help diagnose the issues with Panzer Dragoon's threading and audio issues.  I'll look into those later and find out what's going on.  I hope I'm not the only one who has this game, I could use anyone and everyone's help with it! :(

Shogun.

**Comment by PatrickvL** [comment]
Thanks for the link - I completely forgot about that. Lots of usefull information in there.

**Comment by RadWolfie** [comment]
Not sure if @blueshogun96 or anyone else noticed... It's having a problem creating files in Z: drive due to non-existing folders aren't creating it before create files in it. I had done little bit of troubleshooting, it turns out a file is attempted to create in sprite/font folder first, then it just goes in a loop. Aka spam of IoCreateFile error messages.

**Comment by Sarkie** [comment]
If it's trying to make physical files on your disk, procmon might be useful.

If it's virtual you can ignore me

**Comment by ergo720** [comment]
In version 3ca1a354, the game still has the same problems reported above: the tutorial is playable (but with corrupted graphics) and starting a new game will cause an infinite black screen (the log shows the same IoCreateFile function repeatedly called like it was reported by RadWolfie). The input is randomly broken because it selects the options by itself and if I use the xinput option the game doesn't respond at all. The sound works in the option menu and in the tutorial. Keep in mind that I have a promotional version of this game and I don't know if it is PAL or NTSC. 

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1174440/KrnlDebug.txt)

**Comment by LukeUsher** [comment]
Re: Xinput, are you sure you have an Xinput compatible controller, such as an Xbox 360 or Xbox One pad?

**Comment by ergo720** [comment]
Right, I have a ps2 controller with a usb adaptor that is why it doesn't work with xinput. Thank you for let me noticing this.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#113
