### ISSUE TITLE
[PAL] Ice Age 2 The Meltdown BlockOnTime error

### ISSUE THREAD

**Issue by rexcaptain501** [Cxbx-Reloaded/Cxbx-Reloaded#431]
Tested on Cxbx-Reloaded build 36f9e17, May 3 2017

In Hardware mode, the game will eventually crash with a blueshogun error (* D3D::BlockOnTime not implemented). Software mode has an immediate crash with no audio or video.

Hardware mode crash: ![Photo 1](https://cloud.githubusercontent.com/assets/10300935/25686686/51ba6830-30c4-11e7-9f6e-258cbe930616.PNG)

Ice Age 2 The Meltdown (default.xbe) .xbe info dump: [Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/974990/Xbe.txt)

Hardware mode Kernel Debug file: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/974994/KrnlDebug.txt)

Settings used:

Display Adapter: NVIDIA GeForce GTX 1060 6GB
Direct3D Device: Direct3D HAL (Hardware)
Video Resolution: Automatic (Default)

**Comment by rexcaptain501** [comment]
@blueshogun96 (* D3D::BlockOnTime not implemented)

**Comment by blueshogun96** [comment]
One of us REEEEEEEEALLY needs to get in there and fix that.  Btw, it won't matter what your specs are.  It's a missing or broken signature.  I noticed Luke comments some of these out, but I don't know why (uncommenting two of them fixed the 4920 dashboard for me).  But since I don't have this game personally, I can only assume it's similar to the issue with Turok now.  So I'll fire up turok later on and see what it is because this is coming up far too often.

Shogun.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#109
