### ISSUE TITLE
Project Gotham racing - random crashes

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#444]
Reported here : http://www.emutalk.net/threads/56608-The-still-in-progress-emulator-broken-screenshot-thread-)?p=460631&viewfull=1#post460631

Commit ae13a335
Screenshot : http://www.emutalk.net/attachment.php?attachmentid=40016&stc=1&d=1494001148

**Comment by rexcaptain501** [comment]
I can only get as far as the intro cut scene with pulsing glitchy audio. Once it's finished, an unknown exception code crash error pops up.

.xbe info: [Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1137217/Xbe.txt)

Kernel Debug file: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1137233/KrnlDebug.txt)

Intro cut scene: ![pgr](https://user-images.githubusercontent.com/10300935/28042746-bc5dbd48-6622-11e7-847e-b67ce82803d1.PNG)

Crash: ![pgr crash](https://user-images.githubusercontent.com/10300935/28042760-c6d5f25e-6622-11e7-8154-50644c17c141.PNG)

**Comment by PatrickvL** [comment]
Seems like a patch is not applied, unclear if it's graphics or sound related.

**Comment by rexcaptain501** [comment]
Tested with Cxbx-Reloaded build 3ca1a35, Jul 23 2017

No audio is being output anymore. Getting similar results to #429 (Madagascar).

![2](https://user-images.githubusercontent.com/10300935/28503756-759feff0-7060-11e7-8a5a-2e691415c672.PNG)

**Comment by RadWolfie** [comment]
I'll check this out later this week to see if I can fix the audio part unless someone else will beat me to it. :smile:

**Comment by RadWolfie** [comment]
Hmm... in EmuDSound.cpp at beginning of line 1100 with the code shown below. If removed the if/else check, then audio is playing just fine. Is there some reason for this to be worth keeping? I had checked other playable titles and did not hear any distort or any crash.
```
    if (pThis->EmuBuffer != 0) {
        *ppvAudioPtr1 = pThis->EmuBuffer;
        *pdwAudioBytes1 = dwBytes;
    } else {
        ...
    }
```

By doing this, Project Gotham Racing and Splinter Cell Pandora Tomorrow (online.xbe) titles are audible.

**Comment by PatrickvL** [comment]
@RadWolfie I'm not familiair with the dsound code, so I browsed through it. I still can't determine if your suggestion is right, but it did make me submit a Pull Request for DSound - could you care to review it? https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/537

**Comment by rexcaptain501** [comment]
Tested on Cxbx-Reloaded build aa0c6718, Jul 28 2017

Project Gotham Racing was so desperate to get back to the early 2000s, that it's having it's own little squished 4:3-eque party.

![1](https://user-images.githubusercontent.com/10300935/28712027-acedf35a-73dd-11e7-9282-82f767e39fb9.PNG)

Kernel Debug file: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1182630/KrnlDebug.txt)

**Comment by rexcaptain501** [comment]
Edit: deleted my previous comment. Seemed to be a rendering issue caused by putting video settings to my native resolution instead of auto.

I hadn't seen this behaviour before. Just for reference: ![1](https://user-images.githubusercontent.com/10300935/28712268-bba9c62a-73de-11e7-9faf-8d40644075e0.PNG)

**Comment by LukeUsher** [comment]
That looks like you set your output resolution higher than 640x480, a lot of titles specifically set the viewport to 640x480, in which case you'd get this result.

Other titles scale to the full screen size automatically, so it's not really a bug as such, just a result of how the game was programmed.

**Comment by rexcaptain501** [comment]
That's really weird, because on previous builds to aa0c6718 this didn't happen.

**Comment by PatrickvL** [comment]
Problems with wrongly placed and/or un-streched video's is probably due to a bug in overlay handling. I've been messing around with it already, but nothing to show for it yet.

**Comment by rexcaptain501** [comment]
I just tried again with an older build I was testing with today and I'm getting the same stretch behaviour. Odd. *shrugs*

**Comment by LukeUsher** [comment]
This happens with the majority of titles if you set a resolution higher than the Xbox default, it has always been an issue, and will remain an issue until either full LLE (where we can handle this on the GPU level) or we make our rendering functions (eg: SetViewPort) ignore the values given by the xbox title. 

The first option is a long way away because of the amount of technical work involved

The second option has a high potential for bugs and upscaling is only a nice to have so it likely will be a time before it is implemented properly.

**Comment by rexcaptain501** [comment]
Yeah, I just tested with a8033fee (yesterday) and I'm getting the same behaviour as aa0c671, and I'm sure I didn't get this yesterday with the setting at 1920x1080. Oh well, I guess? Hardware Mode looks the same, only rendered to the monitor. 640x480/auto works just fine as usual.

**Comment by RadWolfie** [comment]
@rexcaptain501 When you set a higher resolution, it will mostly "shrink" the output screen because it doesn't perform "fill to screen" process. However dashboard appear to always fill to screen no matter what the resolution is. Plus by design, the "auto" uses 640x480 resolution by looking at the code in the past. I would say it works as intended.

@PatrickvL [This is the if/else portion I'm talking about which is now at line 1041.](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/src/CxbxKrnl/EmuDSound.cpp#L1041) By removing **"if"** portion, the intro do start playing audio just fine.

**Comment by zaykho** [comment]
@rexcaptain501 
Beware that, if you spot an issue with the latest build, and try to load an older one to compare, you will need also to clean the cxbx-r folder in appdata.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#108
