### ISSUE TITLE
Halo Crash on bootup (=XNetGetEthernetLinkStatus+0x7ab)

### ISSUE THREAD

**Issue by haradons** [Cxbx-Reloaded/Cxbx-Reloaded#479]
Didn't see anything as far as error codes for Halo. As soon as it boots up it crashes. 
![image](https://cloud.githubusercontent.com/assets/13687549/26473660/a5636f74-4161-11e7-8aac-28c8419b1a5b.png)

![image](https://cloud.githubusercontent.com/assets/13687549/26473619/632f68ba-4161-11e7-88ec-c25a0b17ce7a.png)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1030404/KrnlDebug.txt)

**Comment by PatrickvL** [comment]
At some point in time we should compare the symbol addresses we write to our HLE cache file of Halo, to the symbol addresses [Xeon ](http://ngemu.com/threads/xeon-v1-0-released.40464/#post-573790) had in it's `halo.ini` file. Perhaps our symbol detection is still not entirely correct, or we could lack a crucial patch. (Although I'd rather see us patch _less_ instead of _more_ functions.)

**Comment by LukeUsher** [comment]
There are quite a few things going on with Halo that make it problematic to emulate. Xeon had game specifics hacks for it too (There's a flag in the .ini file for a Halo memory hack). 

I do check Halo/work on it quite often, but no notable progress so far. I suspect that once Patrick's Work In Progress branch is merged in, we'll be closer to getting it working, among other things, Halo seems to like creating and using resources without calling Register.

**Comment by blueshogun96** [comment]
@LukeUsher, I do recall that day when sir caustik said that Halo likes to modify its textures at odd times.  I guess that's a hint.  Also, there's a hack where the bunk videos are skipped intentionally.  At one point, I do recall a screenshot of Cxbx running the intro video upside down.  The halo thing was quite a mystery to me as I couldn't quite figure out myself what the issue was.

Shogun

**Comment by PatrickvL** [comment]
I'll definitely look into this one, once my work in progress branch is nearing is completion

**Comment by ergo720** [comment]
Well, with the latest build, it now crashes with a different error.

![halo](https://user-images.githubusercontent.com/30000751/28575105-73d3f722-713f-11e7-8716-2fa579fdf4f0.PNG)

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#95
