### ISSUE TITLE
Website Compatibility page issues

### ISSUE THREAD

**Issue by BiatuAutMiahn** [Cxbx-Reloaded/Cxbx-Reloaded#49]
- When adding an entry, after uploading an xbe, sometimes the fields come back blank and are disabled so no user entry is allowed.
- Allow a notes entry, may be useful for specific issues

**Comment by LukeUsher** [comment]
If the fields are blank, it is because the Xbe its-self has no value for that field, I do need to implement a manual override that's true.

The website as it stands was only thrown together in the space of a couple of hours, it's quite low down on my to-do list right now, but I do have some ideas on further development

**Comment by BiatuAutMiahn** [comment]
I must say good work for only being a couple hours,

**Comment by BiatuAutMiahn** [comment]
@LukeUsher on the compatibility page, if a title boots up and displays solid color that varies as if the emu is working, and also responds to inputs...would we consider that an intro issue? or?

**Comment by PatrickvL** [comment]
This no longer applies
