### ISSUE TITLE
Genma Onimusha Crashes on Boot

### ISSUE THREAD

**Issue by MikeyMK** [Cxbx-Reloaded/Cxbx-Reloaded#494]
Upon starting emulation, the user is immediately met with the following error code: 

![genmaonimushaerror](https://user-images.githubusercontent.com/20745266/27721404-109f9280-5d2e-11e7-9b7d-b83f89f0d8ca.JPG)

Log: 

[GenmaOnimushaKrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1114141/GenmaOnimushaKrnlDebug.txt)

**Comment by LukeUsher** [comment]
Thanks for uploading the log and showing the emulator build version, that's good! We don't get that many good bug reports, so I appreciate that.

However we currently only accept issues from games that actually start, if the game doesn't actually boot and at least play some sound or show a splash screen, it's not useful to create a bug report, simply because the vast majority of titles are at this stage, and we want to concentrate on titles that are close to working for now.

From the Readme:
> Cxbx-Reloaded is in the early stages right now and most games will either crash or do nothing, please do not submit issues for these games.
>I want to know what games actually do something, so if a game displays graphics before crashing, please submit a bug reports containing the error message displayed (if any), screenshots and an Xbe dump (This can be created via [Edit -> Dump Xbe Info To -> File]).
