### ISSUE TITLE
Any news for an android version?

### ISSUE THREAD

**Issue by Mckaos** [Cxbx-Reloaded/Cxbx-Reloaded#495]
Would really like to start testing this in my Nvidia shield, would be amazing to plag Halo on it.

**Comment by LukeUsher** [comment]
It's impossible for an non-x86 port for Cxbx-Reloaded in it's current form.
Non Windows could be possible, eventually, but it will never work without an X86 processor

**Comment by tetration** [comment]
Although it would be pretty hard. I heard that there is the possibility of
adding somekind of layer of translation from x86 to the ARM architecture
smarthphones/tablets use.

However it would demand a lot of processing power and its probably better
if we just wait until cxbx reloaded is a more finished product, before
porting to other platforms or architectures.

On Jul 2, 2017 09:50, "Luke Usher" <notifications@github.com> wrote:

It's impossible for an non-x86 port for Cxbx-Reloaded in it's current form.
Non Windows could be possible, eventually, but it will never work without
an X86 processor

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/495#issuecomment-312490045>,
or mute the thread

**Comment by LukeUsher** [comment]
Okay.

In order to get a working android port there are many (huge) tasks that need to happen first.
#3 and #10 have to be completed and fully implemented, as well as some kind of X86-ARM emulation layer, this is at least a couple of years work at this point, especially in regards to #3. 

The original Cxbx was developed with assumptions that it would be running on Windows, and that certain Windows NT kernel calls will be available, because of this, Cxbx-Reloaded is still rather reliant on Windows internal data structures and functions.
