### ISSUE TITLE
Fallout: Brotherhood of Steel shows a blank screen

### ISSUE THREAD

**Issue by pizzasoda66** [Cxbx-Reloaded/Cxbx-Reloaded#497]
Title

**Comment by LukeUsher** [comment]
This isn't really a helpful issue: You provided no information about what build of the emulator you were using, what version (region, title_id) of the game you were using, and no information on what settings you used in the emulator, or any log output.

Additionally, we currently only accept issues from games that actually start, if the game doesn't actually boot and at least play some sound or show a splash screen, it's not useful to create a bug report, simply because the vast majority of titles are at this stage, and we want to concentrate on titles that are close to working for now.

From the Readme:
> Cxbx-Reloaded is in the early stages right now and most games will either crash or do nothing, please do not submit issues for these games.
>I want to know what games actually do something, so if a game displays graphics before crashing, please submit a bug reports containing the error message displayed (if any), screenshots and an Xbe dump (This can be created via [Edit -> Dump Xbe Info To -> File]).
