### ISSUE TITLE
Constantine - Titles

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#516]
It just shows a couple of titles before stopping. Cxbx doesn't crash and doesn't report any errors on screen, it just stops emulating the game. The sound is a way too fast but I think that is because of the fps being 60.

![constantine1](https://user-images.githubusercontent.com/30000751/28572738-cc43471c-7137-11e7-9807-70d883c61ffd.PNG)
![constantine2](https://user-images.githubusercontent.com/30000751/28572748-d1d97cbe-7137-11e7-95c6-69de49381b85.PNG)

**Comment by blueshogun96** [comment]
The music plays too fast not because of the frame rate but because nobody ever fixed the IDirectSoundStream code.

It works by queueing packets of audio samples, then playing each one as they finish.  Cxbx just doesn't properly queue audio samples, so it immediately begins playing new samples before the previous packet finishes.

Furthermore, Cxbx also doesn't appear to emulate the event handle that is triggered when a sample packet is done streaming.  I'd say that the whole thing needs to be rewritten but LLE is coming so it's not quite as relevant I guess.

Shogun

**Comment by LukeUsher** [comment]
Can you upload a kernel log?
Bug reports are rather useless without them, as we cannot begin to investigate

**Comment by ergo720** [comment]
Yes, your are right LukeUsher, sorry for that. All my games are retail/PAL and dumped from a softmodded xbox via ftp with filezilla (I didn't copy then to the internal disk). My pc is a windows 10, i7-4810mq and gtx 870m. Cxbx version is 3ca1a354

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1173737/KrnlDebug.txt)

**Comment by ergo720** [comment]
Unfortunately, in d44c393 Constantine has regressed: it now either hangs cxbx after displaying the title screens (and forcing to close it from the task manager), crashes with a XID_fCloseDevice function error or (very rarely) crashes with a MPCX related function error. The errors seem a bit random and actually the title still works very often like it did before

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185275/KrnlDebug.txt)
[KrnlDebug-Hang.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1185276/KrnlDebug-Hang.txt)
![constantine](https://user-images.githubusercontent.com/30000751/28748340-e6810996-74a4-11e7-8521-9223981f75bf.PNG)

**Comment by PatrickvL** [comment]
I wish we had a manual for doing regression searches, and actually some people that would follow this procedure, so that all developers have to do, is to analyse & fix the actual breaking change...

**Comment by ergo720** [comment]
By the way, just as reminder I have uploaded xbe dumps for all of my games. Recheck my previous posts if you want them

**Comment by ergo720** [comment]
I was finally able to get an MCPX crash but regrettably I didn't turn on the kernel logging. The Cxbx version doesn't match because it's a locally built copy but I have used the same source as b7556f3
![constantine](https://user-images.githubusercontent.com/30000751/28873850-d3653c42-777e-11e7-9223-66873fdee32f.PNG)

**Comment by RadWolfie** [comment]
@ergo720 Thanks for reporting this, I have discover a missing patch for this. By adding this code,"`CDirectSoundStream_SetFrequency=2b7e10`", in HLE cache file. It has progress even further, yet does not fix audio looping.

After some investigating... it turns out 5233 and 5558 OOPVAs are returning same address for this title. I will investigate further within next few days to make an accurate OOPVA signature to go possible back to 3936 database.

**Comment by ergo720** [comment]
Good news, the regressions have been fixed. In dc9baf3 Constantine doesn't crash anymore. Also, the music now doesn't play so fast as it did before, though I can still hear something like a buzzing sound when it's playing. But the game still shows the same titles as it did before, it doesn't seem to be able to progress any further like @RadWolfie said above.
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1206332/KrnlDebug.txt)

**Comment by RadWolfie** [comment]
For now I can't fix the buzzing sound, I have a higher priority which need to be done before I can continue on add more missing patches for audio. Hopefully after I have finish and polish it up, it should improve support across old to new titles. 🤞

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#89
