### ISSUE TITLE
Show frame rate in window caption

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#574]
Extend the window caption with a frame rate counter, expressed in FPS (Frames Per Second) and ms/f (milliseconds per frame). Update this value once per second, showing the average over the past second. The measure should be taken as the time spend between two consecutive calls to Present(). If implemented correctly, V-sync on should result in at most 60 FPS.

**Comment by Luca1991** [comment]
So if I've understood correctly:
ms/f == the time spend between two consecutive calls to Present(), right?
and
FPS == ms/f*1000, right?

The `Present()` function is the one located in PushBuffer.cpp, right? 

Sorry for all these questions, I'd like to be sure to not make big mistakes.

**Comment by StrikerX3** [comment]
FPS is 1000 / ms/f.

**Comment by PatrickvL** [comment]
You'll want to use the Present call in EmuD3D8.cpp

**Comment by Luca1991** [comment]
@PatrickvL I'm at a good point here, but I need an hint. I've written this function:
`int getFPS() {
	return g_CurrentFPSVal;
}` 
in EmuD3D8.cpp, then I call it from WndMain.cpp (to show the actual FPS count), but the value is never updated. I mean `getFPS()` always return 0. I'm 100% sure that `g_CurrentFPSVal` is updated with the current FPS value (because I used a printf earlier, and I can read the right value form the kernel console).
I've the suspect that this is appening because of different threads, right?
`g_CurrentFPSVal `is declared as static volatile int anyway. 
Any hint?

**Comment by PatrickvL** [comment]
It's not only because of different threads, but also because of different processes. (Read the overview in the wiki for more info.) You'll have to put these counters in shared memory, or send window messages from the emulating process back to the parent (GUI) process...

**Comment by Luca1991** [comment]
@PatrickvL thank you for your hint. I've decided to use the shared memory to store the value. The problem now is that I'm getting an exception (=XID_fCloseDevice+0x3dd5874) when storing the fps value from EmuD3D8 to EmuShared. I don't know why yet, I'm still investigating.

**Comment by PatrickvL** [comment]
This has been implemented in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/598.
A few review remarks are still pending, once these are done, this issue can be closed.

**Comment by ergo720** [comment]
There's a problem with the FPS. In Constantine (cxbx version 223e20d1) the FPS counter reports around 1-3 fps but fraps says it's 60 (1st picture). Also, when cxbx stops emulating the game and I hit stop, the caption with the FPS reappears (2nd picture). The second behaviour doesn't happen in dc9baf3fa3f (3rd picture). The FPS counter seems to be wrong only with this game so this could be a border case.
![const-fps](https://user-images.githubusercontent.com/30000751/29471764-bb4bee5c-8440-11e7-92a0-889dc1b258ad.PNG)
![const-stop](https://user-images.githubusercontent.com/30000751/29471787-d22fbd38-8440-11e7-82f1-2fb5213e7e6a.PNG)
![const-right](https://user-images.githubusercontent.com/30000751/29471799-db73aa6c-8440-11e7-8374-b050bc2638ff.PNG)

**Comment by Luca1991** [comment]
@ergo720 thank you very much for your feedback.
So this issue happen only with the game Costantin, eh? I don't have this game :/

**Comment by ergo720** [comment]
Same thing
![const](https://user-images.githubusercontent.com/30000751/29478540-dd9d9d40-845c-11e7-97a7-7ad1769b0a11.PNG)

**Comment by RadWolfie** [comment]
Personally I believe FPS counter @Luca1991 made is accurate. The only reason it might not be accurate is due to a DX8 signature patch(es) is/are missing for Constantine title. Since it is flickering, not showing stable graphic visual, and title is going to fast. Until Cxbx are fixed for Constantine to be playable, we can ignore this for now. Also be sure to expect this unstable FPS to happen on non-playable titles with similar case.

**Comment by PatrickvL** [comment]
@ergo720 Could you either list what issues are still to be resolved, or close this issue if it's good enough for now?

**Comment by ergo720** [comment]
The only problem is that the FPS counter is not accurate for the game Constantine but as @RadWolfie said this is probably a missing patch-related problem. The other issue regarding the counter still appearing after hitting "Stop Emulation" is probably because this game crashes in an abnormal way (my LED is still green as well after Constantine has crashed). So, because of this, the last issue is probably not FPS-related.

**Comment by PatrickvL** [comment]
Okay, for those two issues, it'd be better to create a separate issue "Remove remnant visual elements after emulation stops/crashes" (or something along those lines), write down some details there, and close this issue.

**Comment by PatrickvL** [comment]
@Luca1991 Do you agree with the above?

**Comment by Luca1991** [comment]
@PatrickvL yes, if the issue is game specific, I'd say to create a new issue to keep it in mind

**Comment by PatrickvL** [comment]
Okay, done : https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/678

With that, closing this issue. Thanks again!
