### ISSUE TITLE
Get XMountUtilityDrive to run unpatched

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#60]
Our goal is to get rid of as many patches as possible. This one,  XMountUtilityDrive, is a valuable candidate

**Comment by LukeUsher** [comment]
For this to work, we need to emulate raw access to the partition headers, like we do with Partition0.
XMountUtilityDrive fails when accessing paths such as Partition1 because it expects to have access to the raw partition header data, but instead finds a folder with the partition name.

If we had some way to detect this, we could have PartitionX.bin files alongside the folders to represent the headers.

**Comment by LukeUsher** [comment]
Additionally, XMountUtilityDrive calls XapiFormatFATVolumeEx, but we can bypass that if we patch the XBE to set fDoFormat as a temporary measure, until we get NtDeviceIoControlFile working for HDD partitions.

**Comment by LukeUsher** [comment]
Tagged as Kernel due to relying on NtDeviceIoControlFile

**Comment by PatrickvL** [comment]
@LukeUsher : Would this be relevant to your recent IOCTL work?

**Comment by LukeUsher** [comment]
Indirectly, yes, so I'll pick this up

**Comment by LukeUsher** [comment]
This is solved as if pull request #795
