### ISSUE TITLE
Log all configuration settings during start of emulation

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#668]
In order to be better able to analyse log files, write all configuration settings at the start of an emulation run.
(At least log: display settings like V-sync, LLE flags, X input selector, etc)
Fort this, use unconditional printf, which should end up in the kernel log file.

**Comment by Luca1991** [comment]
Should we save these infos in EmuShared at startup?

**Comment by RadWolfie** [comment]
I'm not sure what you meant by "save these infos in EmuShared". All it do is save/load the settings from registery. What I believe PatrickvL is suggesting is... somewhere within CxbxKrnlInit function in CxbxKrnl.cpp file is to output the settings there. That way it will be easier for us, developers, to find out what really went wrong with more depth information.

@PatrickvL Please do correct me if I'm wrong.

**Comment by Luca1991** [comment]
@RadWolfie Eh, I'm not sure if we can directly read these values from the kernel process. So I was asking if the idea was to store these values in EmuShared at startup, and then read them from the kernel process (in order to print them in the log file).

**Comment by RadWolfie** [comment]
Yes, we can read these values from kernel process via g_EmuShared class. Here's one of the example being used in [CxbxKrnl.cpp](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/src/CxbxKrnl/CxbxKrnl.cpp#L654-L672) file. If we do not pass down the values, including title's path to xbe file, to kernel process. Then it won't be able to run any titles at all.

The same thing I had done for GetXBAudio(...) function in g_EmuShared class in order to enable/disable certain audio format and audio device selection recently.
