### ISSUE TITLE
Use more meaningful names for HLE cache files

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#746]
---
Currently the HLE cache files are named with an alpha-numeric string. This is very inconvenient if the user wants to upload the cache file to report compatibility issues because as cxbx creates more and more files it will become quite time consuming to find the one corresponding to the game you are searching since you have to open them one by one to check for the name. I suggest to use the name of the game instead of the current string used, if possible.

---

### Screenshots [Errors, Graphics, Glitches, ECT]
![hlecache](https://user-images.githubusercontent.com/30000751/30783726-3a0108a8-a148-11e7-917e-05e00740247d.PNG)

---

**Comment by RadWolfie** [comment]
I wish it is that simple, it's not. Some titles such as Innocent Tears, Splinter Cell: Pandora Tomorrow, etc are multi-xbe bootable with same title names. Here's alternate solutions for this workaround:
1. Show the HLE cache file name of loaded/running xbe in Cxbx's Window (somewhere visible enough).
2. Simplify add Title's name before the alpha-numeric string with a dash.
3. Or **really** simple solution, use your search bar with "file contents" checked from "Advanced options" list. (Windows 8 and below may have different keyword instead of "Advanced options". Use your favorite search engine to find out.)

**Comment by ergo720** [comment]
I opt for the second solution, that way the cache files can also be sorted alphabetically according to the title's name in explorer. The third one is temporary workaround for the moment, though.
