### ISSUE TITLE
Ford Racing 2 giving D3D::BlockOnTime not implemented error

### ISSUE THREAD

**Issue by rexcaptain501** [Cxbx-Reloaded/Cxbx-Reloaded#766]
Self explanatory. Tested on Cxbx-Reloaded build 853eea7b (Oct 11 2017). More details are in the link below.

[game-compatibility #415 link](https://github.com/Cxbx-Reloaded/game-compatibility/issues/415)

**Comment by rexcaptain501** [comment]
@blueshogun96 Ford Racing 2 is giving a D3D::BlockOnTime not implemented error.

**Comment by PatrickvL** [comment]
BlockOnTime is a function that waits until the GPU has processed commands up to some point. Our HLE was originally designed to patch all D3D functions, so no GPU command would be emitted. Cxbx-Reloaded is steering away from this, instead allowing many D3D functions to run unpatched. This results in emitting GPU commands, of which many are just ignored (since we emulate them based on the traces that are left behind in D3D state structures in memory). In the future, we'll be emulating more and more GPU commands themselves, avoiding the importance of locating the D3D state correctly. Until that time however, we're stuck with patches like these. (Also, the GPU command handling code currently gets stuck for unknown reasons, so that will have to be fixed first anyway.)

**Comment by LukeUsher** [comment]
Not an error, just a notice for developers
