### ISSUE TITLE
.deb from Ubuntu PPA

### ISSUE THREAD

**Issue by nitrofurano** [Cxbx-Reloaded/Cxbx-Reloaded#789]
if someone is going to port Cxbx-Reloaded to GNU/Linux, please share an Ubuntu PPA url, or .deb installers - ( btw, i’m specially curious about Chihiro titles! ;) )

**Comment by RadWolfie** [comment]
There will not be a port to Linux in the near future. Cxbx-Reloaded is still in early stage of development. Though, we do welcome anyone whose willing to port it over to Linux.

Also, as of Wine 2.18 and newer. You can officially run Cxbx-Reloaded from Wine software on Linux. Would this be enough for now?

**Comment by LukeUsher** [comment]
Currently, a native Linux port is not possible due to a large dependency on the Windows API, working away from this could be several months, or even years of effort, so I'm closing this for now.

Note that if we do ever get a native linux build, we will publish to the normal software channels (Ubuntu PPA, Archlinux AUR, etc)
