### ISSUE TITLE
DirectSoundCreate8 Failed!

### ISSUE THREAD

**Issue by romaxy151** [Cxbx-Reloaded/Cxbx-Reloaded#827]
All games here such error
I understand this is a bug with sound.
![default](https://user-images.githubusercontent.com/30557931/34522985-26ec54a2-f09e-11e7-8d4a-4ebf2e0f4b57.PNG)

**Arx Fatalis**
[KrnlDebug1.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1600505/KrnlDebug1.txt)
[Xbe1.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1600506/Xbe1.txt)

**4X4 EVO 2**
[KrnlDebug2.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1600511/KrnlDebug2.txt)
[Xbe2.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1600512/Xbe2.txt)

**Comment by LukeUsher** [comment]
This seems like your registry settings got corrupted somehow, what happens if you try to edit the audio settings in Cxbx-Reloaded?

It shouldn't happen, but occasionally the registry keys become corrupted, if this happens you can delete them using regedit by navigating to HKEY_CURRENT_USER\Software\Cxbx-Reloaded.

**Comment by BiatuAutMiahn** [comment]
yep, same issue here, one of the devs on discus mentioned to have implement a check before reg is written to avoid corrupt entries like this

**Comment by romaxy151** [comment]
Thanks, deleted the HKEY_CURRENT_USER\Software\Cxbx-Reloaded and it worked.
