### ISSUE TITLE
Support Compressed Game File Type

### ISSUE THREAD

**Issue by trymeouteh** [Cxbx-Reloaded/Cxbx-Reloaded#834]
This reddit post shows people how to compress there games files with other consoles.

https://www.reddit.com/r/emulation/comments/3g933n/guide_reduce_the_size_of_your_ps2_gc_wii_x360_ds/

I think it would be handy if CXBX-Reloaded considered doing something like this. Since Xbox Games are kinda large in size. Making them smaller in size and be able to run them it would be useful especially if a user has a lot of Xbox Games.

A good option in my opinion is to do what PCSX2 did which was allow gzip files to be opened as games.

**Comment by PatrickvL** [comment]
This issue is closely related to https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/205#issuecomment-283506688 which talks about XISO support.

Both that and compressed archives are currently not supported because Cxbx-Reloaded opens all it's files using regular Windows file handling API's, which can't access files stored within archives.

So, to support (compressed) file system containers, we must first reimplement all kernel file access API's. That's a lot of work, which is currently not high on our priority list.

I did start a branch long ago to try out TFS (tiny file system, which could potentially supports all storage types you could think of), but that didn't get very far.

**Comment by LukeUsher** [comment]
There's also the fact that Cxbx-Reloaded runs extracted ISOs rather than raw dumps of Xbox games. Raw xiso dumps are ~8GB each due to padding and other things, but extracted filesystem dumps are usually much smaller: the majority of games being 1GB or less, so this isn't that much of an issue for us at the moment

**Comment by JayFoxRox** [comment]
**[As this issue was also posted on the XQEMU,  I've responded there](https://github.com/espes/xqemu/issues/105#issuecomment-355612159). I'll add some more thoughts here for completeness.**

First, in addition, I'd say that the original article is extremly misleading. It employs a lossy compression for Xbox 360 images (which is about what we'd have to do for Xbox) which will possibly render your backups unplayable in accurate LLE.

[A more recent post on reddit also compares some compression formats](https://www.reddit.com/r/emulation/comments/7o4h58/quick_compression_method_comparison/) (which also tests what I've suggested in my response, seperating compression from the emulator). Note that the Xbox had compressed audio and WMV support. Almost all games will already be compressed. I'd assume they compress worse than Playstation 2 games.

The major exception is the security / padding data, but that has a high entropy, so it won't compress at all. The posted Xbox 360 guide drops this data, as I previously mentioned. My strategy to remove / drop this data losslessly only works for older games, until someone finds a critical flaw in RC4-drop-2048 (which is unlikely). *If* this is implemented, however, it should be implemented in an external tool or lib, not necessarily as part of the emulator (for a couple of reasons).

A technical implementation for streaming using standard package formats (such as zip) is extremly bad for Xbox as we need a format which can compress block-wise.
So we'd always require a not-so-common solution or file format. Because unlike for N64 with small ROMs, users don't want to wait a couple of minutes for a full game extraction (which will also require a lot of disk space all of sudden ~ 8GB).
I think it would be ugly to contanimate the emulator code with such compression crap, too.

If you are worried about filesystem space, you should probably use a system-wide compressing filesystem in the first place. Don't shift your / your OS responsibility into our realm. Xbox emulation is complicated enough as-is.

**Comment by BiatuAutMiahn** [comment]
well, 7zip works with streams, which you should be able to extract only needed data. Recently I was working  on a 7z module for Autoit3 Script, where we can stream file data into a buffer. So why not just 7z games in flat format (not in iso, althou 7z supports iso, mod would be needed for xiso), keep an index of the disc structure, file indices within the archive, open a stream dump the blocks requested.

The problem however is with HLE, how to map buffer to a file handle without writing to disk?

**Comment by PatrickvL** [comment]
CHD files seem like a potentially useable format for this. https://github.com/rtissera/libchdr

**Comment by PatrickvL** [comment]
This issue is related to issue #205 (XISO support)

**Comment by LukeUsher** [comment]
Closing as we probably won't fix this: We may support XISO in the future, but we have a separate issue for that.

**Comment by mirh** [comment]
http://forum.redump.org/topic/23083/xbox-shrinking-tool-needed/
Jay made a tool, and there was also some discussion here.
