### ISSUE TITLE
Move non-kernel code outside CxbxKrnl folder

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#870]
Currently, things like hardware emulation and other non-kernel code, resides in the CxbxKrnl folder. Partly, this is due to the fact some functions reside in kernel-implementation files (EmuKrnl*.c). Partly, it's because files were already there historically, or placed there to keep everything emulation-related together.

Let's improve that, by moving functions and entire files to a sane file and folder.
One good example is how MAME organizes it's files.

For this issue, seek code that isn't in a logical location, decide where it should reside, move it, make sure everything keeps compiling (release AND debug builds), and submit it in small increments.

NOTE: Do NOT change functionallity! The only changes allowed are those required to move code!

**Comment by LukeUsher** [comment]
The CxbxKrnl folder is purely a remnant when Cxbx contained only the GUI and all emulator code was contained in an external DLL, back when Cxbx used to generate EXE files rather than launch Xbe files directly.  

Nowadays the whole project structure could be much better.

We no longer need a Cxbx and CxbxKrnl folder, instead we should structure it based on usage.

I propose having a folder for GUI, a folder for Hardware, a folder for HLE (containing the HLE implementations for XDK libraries such as D3D, DSOUND and XAPI) and also a HLEKernel folder, containing the HLE Xboxkrnl implementation. 

The above structure mostly exists already in the MSVC solution, but the physical location of the files don't follow the same structure.

**Comment by PatrickvL** [comment]
A first step could be to rename CxbxKrnl into HLE/kernel

**Comment by x1nixmzeng** [comment]
For historical reasons the files should be moved correctly under git, not just copy-pasted into a new folder!

**Comment by PatrickvL** [comment]
@x1nixmzeng from http://www.syntevo.com/doc/plugins/servlet/mobile?contentId=3113202#content/view/3113079 :
> Moving/Renaming Files

> In general, Git's move/rename tracking happens always on-the-fly, e.g. when logging or blaming a file. Hence, there is no need for an explicit move operation: just move your files with your favorite tools (IDE, file explorer, from command line).

> Still, Git offers a git move command for convenience which performs a normal file system move and then stages the removed and the newly added file to the Index. For a GUI client like SmartGit, providing such an operation is not necessary. Still, because users are frequently confused about the missing move operation, SmartGit provides Local|Rename.

> Contrary to git status SmartGit's status display does not denote moved files; on-the-fly moves will only be calculated for history-related functions like Log or Blame.

**Comment by PatrickvL** [comment]
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/884 moved hardware devices to `src\devices` and all video-related hardware files to `src\devices\video`.

**Comment by ergo720** [comment]
Done in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1516, closing.
