### ISSUE TITLE
Avoid kernel logfile overwriting

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#880]
Currently, if kernel logging is enabled, Cxbx-Reloaded overwrites the configured log file with the output of each new Xbe that's being launched. This is especially frustrating when multi-xbe titles are being used, or when the dashboard is launched (as contents of prior runs are lost).

For this issue:
* devise one or more solutions for this problem
* discuss the pro's and con's of each suggestion before implementing it
* reach consensus
* implement
* deliver

A quick overview of possible solutions:
* put a logfile next to each Xbe that's being emulated (pro : avoids most overwriting, con : pollutes title folders)
* ask the user to what file must be logged (pro : user becomes responsible, con : cumbersome to use)
* use a naming convention that prevents overwrites (pro : avoids most overwriting, con : logfiles pile up)
... etc

**Comment by gandalfthewhite19890404** [comment]
Some suggestions:
1. Make one log file for one session. Session started as Start emulation button is pressed. Session ended by error(crash) or stopping emulation (by user or shutdown command from dash for example).
2. Naming log file - Title, ID or other unique. Also it may consist timestamp (additionally).

**Comment by RadWolfie** [comment]
This ticket is outdated since pull request https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1395 introduced new feature to append to active log file than overwrite it.

**Comment by PatrickvL** [comment]
The fact logging is now appended covers only part of this issue. It doesn't cover (optional) creation of separate log files for separate xbe's.

**Comment by RadWolfie** [comment]
I'm sorry, do we even need separate log files for separate xbes? I don't see how this would be viable information when it should be confined to one log file. If multi-xbe is used, it can use one log file for launch, run gameplay, and the like activities. Otherwise, other log file will contain menu, cutscenes, etc activities. It only lead to confusion which log file contain the crash or last used. I'm keen to close this issue as we have enough feature set to able debug the issue.

**Comment by Masamune3210** [comment]
This would end very poorly for games with lots of separate xbe's, of which many exist
