### ISSUE TITLE
Trampolines fail on some patched functions

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#952]
https://github.com/Cxbx-Reloaded/game-compatibility/issues/95 seems to imply trampolines don't always work, even though the function itself is already patched.

Investigate the reported case linked above to see if this behaviour is reproducible, and if so, try to determine what's going on here. Ultimately, create a solution.

**Comment by LukeUsher** [comment]
Usually when this happens it's due to an unimplemented assembly instruction within subook, this generally requires disassembling the title to work out which opcode fails and then updating subhook's opcode decoder, for an example, see 

https://github.com/Cxbx-Reloaded/subhook/commit/e562d10d4d88f85a8b5475139c68696dfc6bf231

**Comment by jarupxx** [comment]
I am sorry for making you confused. This is a matter of my repository. This issue looks to have occurred because I am not updating the submodule.

**Comment by LukeUsher** [comment]
Thanks for checking in, I'll close this, then
