### ISSUE TITLE
bisect turok

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/Cxbx-Reloaded#991]
Turok menus regressed - bisect and report findings here

**Comment by Paradise12314** [comment]
I'm not sure what type of Regression you have on Turok, but I've had serious graphical corruption since a Commit back in February. 

On Appveyor, it's called "GetVertexBufferSize wasn't taking offset into account: This fixes Zapper!" 

The Videos play fine, but almost all the Menu is Black, running at around 4fps and also makes my Desktop flicker like crazy. It is the same from that one right up to the latest version. It was fine and mega fast before that Commit. 

Specs:
i5 2500 3.3Ghz
8gb Dual Channel DDR2
512mb 9500gt DDR2 Driver 341.44

If your wondering why such a bad Card with that CPU, I did have a GTX 560ti till it died, leaving me with this old Relic lol.

Video playing fine:
![video](https://user-images.githubusercontent.com/24655069/37401374-c3e9ebd0-277f-11e8-9abf-d8c9ebf943a6.jpg)

Bad Commit Menu:
![bad](https://user-images.githubusercontent.com/24655069/37401386-cdd30a32-277f-11e8-8787-ec02f6824585.jpg)

Previous Good Commit Menu:
![good](https://user-images.githubusercontent.com/24655069/37401408-d7d84aba-277f-11e8-9ba6-603147321ffd.jpg)

**Comment by PatrickvL** [comment]
Thanks for digging into this! Am I correct assuming the is the culprit ? https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/151c5963bae96adff0c880799b17f3af400bcc43

**Comment by Paradise12314** [comment]
Yes that's the one. I'm confused though. JohnGoodGames used a more recent version than that, and it's fine. His Video is on YouTube. He uses a GTX 1080 though. Perhaps 151c596 broken old DX10 Cards only?

**Comment by PatrickvL** [comment]
I can't verify your findings - for me the menu has been corrupted much longer. I'm doing a bisect too...

**Comment by jarupxx** [comment]
I use GTX 750ti works up to PR 954, perhaps PR https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/956 broken.

PR 956 broken
![turok](https://user-images.githubusercontent.com/20138367/37554520-98913222-2a1d-11e8-85a0-e34076cd1bd4.jpg)
PR 954
![turokok](https://user-images.githubusercontent.com/20138367/37554537-c7f3bb20-2a1d-11e8-8a48-3d6e90bc1fbd.jpg)

**Comment by PatrickvL** [comment]
Thanks. Let's see if others can reproduce that too..

**Comment by PatrickvL** [comment]
@LukeUsher If indeed #956 broke Turok menus, then perhaps that's due to the removal of the StateBlock patches?

**Comment by JohnGodgames** [comment]
100% comes from PR https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/956

<img width="481" alt="turok 1" src="https://user-images.githubusercontent.com/11453507/38537328-3dab0b2a-3c8e-11e8-83d7-4877c27d89fd.PNG">

<img width="481" alt="turok not working" src="https://user-images.githubusercontent.com/11453507/38537337-4b6de96c-3c8e-11e8-8250-629197e35aa0.PNG">

**Comment by PatrickvL** [comment]
Luke is working on this - his result looked like this a few days ago : 

![](https://cdn.discordapp.com/attachments/293096509019258880/433938747843936266/unknown.png)

**Comment by LukeUsher** [comment]
Turok regressed when we switched over to the Dxbx based pixel shader conversion. The issue is related to when titles use RenderState/TextureState functions to modify the shader.

Fixing this functionality restores Turok, but breaks JSRF.

Maybe we need to port the RenderState code from WIP_LessVertexPatching so we can remove those patches and read from the D3D state directly.

**Comment by PatrickvL** [comment]
I can confirm it's rendering correctly again - but I'm not entirely sure which commit actually fixed it...
